### ISSUE TITLE
config dialog width and height, or style attributte

### ISSUE THREAD

**Issue by minipai** [likeastore/ngDialog#100]
I am using ngDialog to show a image, and I want the .ngdialog-content has exact same size of my image.
So I need to set ngdialog-content's size dynamically so its not possible to set it in css.

Please consider add a option to allow direct set style attribute of .ngdialog-content

**Comment by jipson7** [comment]
@geshido Sorry to raise this old issue. But do you know any variation of your solution that would work on ie8? Thanks for the answer regardless, saved me a headache.

**Comment by geshido** [comment]
@jipson7, unfortunately I don't have any possibility to check this solution in ie8, because of my Linux system, sorry
