### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'splice' of undefined" when performCloseDialog

### ISSUE THREAD

**Issue by gustavHsiung** [likeastore/ngDialog#101]
I am using a simple external template, this error comes up when I click on outer area and also the default close icon. I guess it is because ngDialog try to remove Hammer.js tab event. The error goes away if i comment off line 77 in ngDialog.js.

How can I fix it? Thanks!

**Comment by bhargav123** [comment]
bower update 
thats it

**Comment by voronianski** [comment]
@bhargav123 everything's fine?

**Comment by bhargav123** [comment]
yes voronianski
