### ISSUE TITLE
ng-include not working inside template

### ISSUE THREAD

**Issue by DTFagus** [likeastore/ngDialog#112]
Hey Folks,

if I have a template like this:

```
<div class="omb_login">
   <div  ng-include="modals/LoginModal/steps/step1.tpl.html"></div>

  </div>
```

the ng-include does not work. The template seems to be correctly put into template cache.
Any suggestions?

Thank you

DTFagus

**Comment by MbF-Vijay** [comment]
`<div ng-include="'partial/copy/confirm-text.html'"></div>`

Put correct way but not working when upload on live URL


```
<script type="text/ng-template" id="termsUpdate">
    <div class="clearfix component-block"> 
      Your information has been updated successfully.
      <button class="btn btn-small" ng-click="closePopuptermsUpdate()">Okay</button>
    </div>
</script>
```

I got 403 error, What should I do?
