### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by grabbou** [likeastore/ngDialog#118]
Any plans of developing them? If we will have a nice codebase to start with, I can help you guys with writing the rest of the stuff.

**Comment by grabbou** [comment]
@voronianski any chances for having the skeleton? If not - I can do it by myself.

**Comment by voronianski** [comment]
@grabbou sorry, you're free to start with it then

**Comment by grabbou** [comment]
Cool, thanks. I'll keep this topic updated once I have more things to show you. I think the best thing we can do is to commit the skeleton and once it's filled in with simple scenarios, allow others to write other tests as well.
