### ISSUE TITLE
Auto-size dialog based on inner content

### ISSUE THREAD

**Issue by thoughtpalette** [likeastore/ngDialog#120]
Wondering if this could be a PR. Something similar to how http://fancyapps.com/fancybox/ works.

Right now if the content is too big, due to hard top-padding you have to scroll the whole page rather than the padding changing dynamically.

**Comment by egor-smirnov** [comment]
@thoughtpalette sure, you could submit a PR. Just use this as an options which is by default `false`.

**Comment by egor-smirnov** [comment]
Closing this issue as it's quite old.

I like the idea. 
@thoughtpalette PR for this feature is always welcome!
