### ISSUE TITLE
Dynamic width?

### ISSUE THREAD

**Issue by TomsonNgassa** [likeastore/ngDialog#121]
Is there a way to dynamically set the set the width of the dialog

**Comment by minutephp** [comment]
Hi, 

sometimes it is difficult to use CSS, say a light-box which changes the dialog sizes based on the size of image inside? that is a very common thing for a modal dialog to do. 

I'm willing to write the code for dynamic width calculation if you guys are interested.

thanks

**Comment by egor-smirnov** [comment]
@minutephp sure, go ahead. Looks like it's one of the most requested features.

**Comment by minutephp** [comment]
awesome.. since i'm new to this library, please give me a few pointers to help me get started:

1) I think I should check the width on $(window).resize
2) What is the best way to know when the contents inside have changed? checking innerWidth on digest cycle is one option but is there some other more cpu friendly way?
3) After calculating the width, I should do something like this:
     $('.ngdialog-content').css('max-width', screenWidth - 20).css('width', calculatedWidth)

Am i on the right track?

**Comment by TomsonNgassa** [comment]
That will be great.

Thanks

Tomson

On Jun 26, 2015 07:58, Minute PHP <notifications@github.com> wrote:

Hi,

sometimes it is difficult to use CSS, say a light-box which changes the dialog sizes based on the size of image inside? that is a very common thing for a modal dialog to do.

I'm willing to write the code for dynamic width calculation if you guys are interested.

thanks

—
Reply to this email directly or view it on GitHub<https://github.com/likeastore/ngDialog/issues/121#issuecomment-115655559>.

________________________________
Important: This email is intended for the above named only and may be confidential, proprietary, and/or legally privileged. If this email has come to you in error, you must take no action on it, nor may you copy or show it to anyone. Please contact the sender and delete the material from any computer.
________________________________
Important: This email is intended for the above named only and may be confidential, proprietary, and/or legally privileged. If this email has come to you in error, you must take no action on it, nor may you copy or show it to anyone. Please contact the sender and delete the material from any computer.
