### ISSUE TITLE
server.js doesn't resolve

### ISSUE THREAD

**Issue by thoughtpalette** [likeastore/ngDialog#122]
Probably a PEBKAC issue.

Reproduce:
`clone repo`
`npm install`
`bower install`
`node example/server.js`

![ngdialog](https://cloud.githubusercontent.com/assets/690624/4945068/d376b6a0-6603-11e4-8b27-4c403dad0bfc.jpg)

**Comment by richardszalay** [comment]
I had the same issue. `server.js` assumes it will be run _in_ example.

ie.
```
clone repo
npm install
bower install
cd example
node server.js
```
