### ISSUE TITLE
backface-visibility breaks on chrome

### ISSUE THREAD

**Issue by yogeshvm** [likeastore/ngDialog#123]
`.ngdialog-overlay` CSS class uses `-webkit-backface-visibility: hidden;` this  CSS property currently has a broken behaviour in Chrome ( see http://css-tricks.com/almanac/properties/b/backface-visibility/)

I am trying to create a new theme which will override `.ngdialog-overlay` and set its `display: none;`, but this doesn't work well in Chrome, and any change in input elements or position of the elements doesn't get rendered correctly.

**Comment by egor-smirnov** [comment]
@yogeshvm do you have any progress on this?

**Comment by egor-smirnov** [comment]
Closing this issue as it's quite old and there is not enough code examples inside it to make any further progress.

Feel free to open new issue with live code example at http://plnkr.co/.
