### ISSUE TITLE
closeThisDialog() removed even if another dialog is opened

### ISSUE THREAD

**Issue by darkoromanov** [likeastore/ngDialog#125]
If you open 2 stacked dialogs and you close one programmatically using 

ngDialog.close();

it will remove closeThisDialog() from the $scope, even it's still needed by the second dialog.

**Comment by sjke** [comment]
:up:

**Comment by Snow-Okami** [comment]
Thanks for this, was pulling my hair out for about an hour trying to figure out what was happening here thinking it was something I was doing. Came here to check out the issues and saw this, sure enough using the updated master fixed this issue for me.

Thanks again for this!

**Comment by EdenZhao** [comment]
Is there any other way to avoid this bug without update the ng-dialog lib?
we still need to close previously opened dialog, but what if we uses some other methods?
