### ISSUE TITLE
Option to allow clicking through the wrapping div

### ISSUE THREAD

**Issue by denjones** [likeastore/ngDialog#126]
Thanks for providing overlay option mentioned in https://github.com/likeastore/ngDialog/issues/117

But what I really want is that I hide the overlay and I can click the elements which were originally covered by the overlay. 

Now the overlay was hided but the event delivery was still blocked. (T.T )

**Comment by faceleg** [comment]
Pretty sure this has been fixed, see: https://github.com/likeastore/ngDialog/blob/master/css/ngDialog.css#L81-L97
