### ISSUE TITLE
ngDialog appendTo ng-repeat problem

### ISSUE THREAD

**Issue by sick** [likeastore/ngDialog#127]
The dialog box simply disappears when updating the object to which it is bound.
Open the dialog with the appendTo: #id (iobject from ng-repeat).
Then here https://sick.firebaseio.com/ update clicked object value and the dialog disappears. He seemed to lose object #id.

http://jsfiddle.net/g1hguv37/13/

Btw, thanks for the great tool.

**Comment by egor-smirnov** [comment]
@sick Could you update your jsfiddle please? As for now it outputs "FIREBASE WARNING: Firebase error. Please ensure that you spelled the name of your Firebase correctly (https://sick.firebaseio.com) " and no data is loaded thus it's not possible to see an issue. Thanks.

**Comment by sick** [comment]
It was about 7 months ago :) You can close this issue.
