### ISSUE TITLE
Open of Undefined Error

### ISSUE THREAD

**Issue by andym5m** [likeastore/ngDialog#128]
I keep getting the following error, I'm using Angular 1.2.2

````TypeError: Cannot read property 'open' of undefined````

What would cause this?

**Comment by grabbou** [comment]
Can you try to reproduce your issue with PasteBin / JSFiddle? @andym5m

**Comment by egor-smirnov** [comment]
ping @andym5m

**Comment by egor-smirnov** [comment]
Closing this issue as it's quite old and data provided is not enough to move forward.

Feel free to open the new issue with jsfiddle / plunker provided. Thanks.
