### ISSUE TITLE
performCloseDialog throws error if debug information option on $compileProvider is not enabled

### ISSUE THREAD

**Issue by tmair** [likeastore/ngDialog#129]
Within the `performCloseDialog` function a call to `$dialog.scope()` is performed. The call returns `undefined` if the `$compileProvider.debugInfoEnabled` option is set to false, because scope information is not accessible on the DOM node anymore.

Maybe this explains the problem but I it might be another problem: https://groups.google.com/forum/#!topic/angular/QTrUP5oz7Nw

**Comment by faceleg** [comment]
Does this still occur in 0.5.5?
