### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by andrew-luhring** [likeastore/ngDialog#131]
[Is this safe?](https://github.com/likeastore/ngDialog/blob/master/js/ngDialog.js#L320)

Because this allows you to inject script elements rather than plain text:

```
ngDialog.open({
  template: '<script>window.alert("vulnerable");</script>'
, plain : true
});
```
Having an option for 'plain' text seems fine if there's some mechanism preventing markup from being inserted. 

Just using a template though:
```
ngDialog.open({
  template: '<script>window.alert("vulnerable");</script>'
});
```

fails because ngDialog is treating the property "template" as a "templateUrl" by default...

*** 

The behavior I was expecting was:

```{ template: '(any html)' }```
would be passed straight through to the directive

```
{ 
   template: '(any html)'
,  plain: true
}
```
 would be escaped using angular sanitization

and

```
{ templateUrl: '(url)' }
```
would just be passed along to the directives' templateUrl property...

There's also nothing to prevent cross-site scripts from being used:
```js
ngDialog.open({
  templateUrl: '(not a nice place)'
});
```

Shouldn't urls be treated as relative by default and then allow users to opt in to external resources?

```js
ngDialog.open({
  templateUrl: '(not a nice place)'
, relative : false
});
```

I can submit a pr if you want.

**Comment by grabbou** [comment]
@andrew-luhring 

In my project, URL's are relative. It has nothing to do with the library, it's how your browser treats the location and url. 

Again, cross-site scripts are up to scripts maintainers, not to us.

Although I agree that renaming `template` property to `templateUrl` would make it more similar to core angular structure, I am afraid of introducing breaking change. 

Let's see what others think about that.

**Comment by egor-smirnov** [comment]
@andrew-luhring I would say it's safe to the degree of safety that Angular gives us. As this is handled by Angular.

@grabbou what you have written about template / templateUrl makes sense. It could be done eventually, though we have issues with more priority currently. So, PR is welcome. Just let me know beforehand if you want to do this template / templateUrl thing.
