### ISSUE TITLE
Template content return "[Object, object]"

### ISSUE THREAD

**Issue by josephi** [likeastore/ngDialog#133]
Hi,

You remove from the last version verification if template is string 
if doesn't take template.data
 
template = angular.isString(template) ?
						        template :
								template.data && angular.isString(template.data) ?
									template.data :
									'';
without this return content template "[Object, object]"
line 188

**Comment by egor-smirnov** [comment]
Closing this issue as a lot of time passed since its opening and it's hard to understand if the issue still in the latest codebase or not. Sorry for inconvenience and hoping for your understanding.

Feel free to open a new issue with live code example in jsfiddle / plunker.
