### ISSUE TITLE
Scrolling is not compatible with the body instead of the container

### ISSUE THREAD

**Issue by vutran** [likeastore/ngDialog#143]
Since the scrolling mechanism of ngDialog is within the container instead of the body, this cause compatibility issues with other modules such as [ngInfiniteScroll](http://binarymuse.github.io/ngInfiniteScroll/)

**Comment by mk-lviv** [comment]
+

**Comment by mateatslc** [comment]
wouldn't setting `infinite-scroll-disabled` param to `true` help with that?
