### ISSUE TITLE
require() via webpack broken

### ISSUE THREAD

**Issue by jozanza** [likeastore/ngDialog#144]
Hey guys,

In [this commit](https://github.com/likeastore/ngDialog/commit/a4195c66a9d5e63be2c0a5853a5e7d7d5017e725#diff-2), I noticed that on line 18 of ngDialog.js, `this` is being passed into the closure rather than `window`. While it may work when `this===window`, it breaks otherwise (such as when requiring this module from within a closure, e.g. webpack).

Do you mind if we change `this` back to `window` on line 18 of ngDialog.js? Thanks.

**Comment by thetutlage** [comment]
Yes it is still broken , refer to this thread 
http://stackoverflow.com/questions/26229323/webpack-and-modernizr-causes-typeerror-document-is-undefined-error
