### ISSUE TITLE
closeThisDialog doesn't work

### ISSUE THREAD

**Issue by whwnow** [likeastore/ngDialog#145]
when I use  "xxxController as xxx" for controller in options  , the method closeThisDialog doesn't work..

**Comment by IncarVishnu** [comment]
+1

**Comment by bluee** [comment]
I had the same problem. The issue seems to be that as a default preCloseCallback is being called but not returning any value.

Solution - Comment out preCloseCallBack in the demo:
```
		app.config(['ngDialogProvider', function (ngDialogProvider) {
			ngDialogProvider.setDefaults({
				className: 'ngdialog-theme-default',
				plain: false,
				showClose: true,
				closeByDocument: true,
				closeByEscape: true,
				appendTo: false,
				//preCloseCallback: function () {
				//	console.log('default pre-close callback');
				//}
			});
```

**Comment by dllen** [comment]
+1

**Comment by sikko** [comment]
Same issue here. When using controllerAs syntax, vm.closeThisDialog() doesn't exist..

**Comment by faceleg** [comment]
Is this fixed in the latest build? 

If not, there are now tests in https://github.com/likeastore/ngDialog/blob/master/tests/unit/ngDialog_closeThisDialog.js that can be added to for testing controllerAs.

**Comment by xuhcc** [comment]
+1
I am using ngDialog v0.5.6, still not fixed.

**Comment by faceleg** [comment]
Until someone fixes this with a PR (hint hint), you can do:

`vm.closeThisDialog = $scope.closeThisDialog`

**Comment by kabrice** [comment]
+1
