### ISSUE TITLE
closePromise not works as expected

### ISSUE THREAD

**Issue by aki-russia** [likeastore/ngDialog#149]
Here is [jsFiddle](http://jsfiddle.net/xu8ssw2k/3/).

```
var dialog = ngDialog.open({            
  template: '<div>Dialog</div>',
  plain: true,
  scope:$scope
});
        
dialog.closePromise.then(function(){
  ngDialog.open({            
    template: '<div>One more dialog</div>',
    plain: true,
    scope:$scope
  });
});
```

I'm expecting to see one more dialog after closing the first one, but it doesn't happen.

It is not work even if I using different scopes for each dialog — [jsfiddle](http://jsfiddle.net/xu8ssw2k/2/)

**Comment by curts** [comment]
It seems to be an issue with the close call (it is closing all ngDialog instances prematurely).  In the interim, as a work-around, if you close the dialog using other means, e.g. `closeThisDialog` (see this modified fiddle - http://jsfiddle.net/xu8ssw2k/6/) then it seems to do what you want.  I'm not sure this will work for your situation, but thought I would pass the idea along until a fix can be created.

**Comment by faceleg** [comment]
Is this still an issue?
