### ISSUE TITLE
Re-open modal too quickly

### ISSUE THREAD

**Issue by maximeloizeau** [likeastore/ngDialog#153]
Hello,
I encounter a possible bug in this case : 
- Opening a confirm dialog
- On close, checking something with data from the dialog
- and in case of negative result, reopening of the dialog

--> the new dialog is unresponsive (ng-click, ng-submit not calling the functions but a console.log in the controller is executed)

I added a $timeout of 500ms before reopening the dialog and it works fine. Below that it doesn't.

Here is my code, in case that what not clear enough.

```
$scope.showPasswordDialog = function() {
        ngDialog.openConfirm({
            template: 'views/public/login.html',
            controller: ['$scope', function($scope) {
                console.log("Controller init");
                $scope.submitPassword = function() {
                    console.log("Password submitted");
                    $scope.confirm($scope.calendarPassword);
                };
            }]
        }).then(function(data) {
            // Password submitted
            User.setAuthorization($scope.calendarId, data);
            $scope.displayCalendar();
        }, function(reason) {
            // Popup closed
            $location.path('/home');
        });  
    };

    $scope.displayCalendar = function() {
        CalendarService.getCalendar($scope.calendarId)
        .success(function(data) {
            $scope.calendar = data;
            $scope.userCells = User.getOpenedCells($scope.calendarId);

            CalendarService.getCalendarCellsDisplay($scope.calendarId)
            .success(function(data) {
                $scope.cells = data;
            })
            .error(function(msg, code) {
                // Error handling       
            });
        })
        .error(function(msg, code) {
            User.resetLogin();

            // Fix for the popup not working when opened too quickly
            $timeout(function() {
               $scope.showPasswordDialog(); 
            }, 500);
        });
    };
```

If someone can confirm/deny this issue, thank you in advance. I don't really know what could cause this.

**Comment by varshard** [comment]
I believe this issue is caused by ngDialog's $timeout.

**Comment by gcacace** [comment]
I am having a similar issue, with open, not openConfirm, trying to open a brand new popup in the closePremise implementation.

**Comment by jonlil** [comment]
Also having similar issue. Having an radio box with ng-change that fires closeThisDialog.
If i try to re-open same dialog to quickly it's not getting closed. Smells like $digest

**Comment by gcacace** [comment]
Temporary solved using:
```javascript
scope.$evalAsync(function() {
    dialog.close();
});
```
but, of course, it's an owful workaround.
