### ISSUE TITLE
Call dialog.close too early cause $dialog is undefined

### ISSUE THREAD

**Issue by varshard** [likeastore/ngDialog#155]
Hello,

Thank you very much. Your module really great and convenience.

I encounter a possible bug in case that I call dialog.close too early like this:

    var dialog = ngDialog.open({
        template: 'templates/progress.html',
        closeByEscape: false,
        showClose: false,
        closeByDocument: false
      });

    //do something
    dialog.close();

Sometime dialog.close() will be executed before the $dialog can be compiled on the line 266.

I've tried printing a log inside the $timeout and sometime the log will be shown after the dialog.close is executed and cause an error.

**Comment by varshard** [comment]
Currently I'm working around this issue by  wrapping dialog.close() inside a 100ms $timeout.

**Comment by egor-smirnov** [comment]
@varshard As soon as dialog opened it emits `ngDialog.opened` event to `$rootScope`. So, you will have write (insetad of `dialog.close()`):

```javascript
$rootScope.on('ngDialog.opened', function() {dialog.close();});
```
