### ISSUE TITLE
Raising modal scrolls document to top

### ISSUE THREAD

**Issue by jclarke0000** [likeastore/ngDialog#156]
When the document is scrolled down, raising a modal first scrolls the document to the top.  This behaviour is particularly problematic in endless scrolling screens -- the second the modal is raised, the user loses their position when returning to the document.

It looks like this is a consequence of using absolute positioning for the modal. This can be remedied by using fixed positioning for the modal and the screen veil, but it doesn't appear that this can be remedied with CSS alone.

**Comment by peimelo** [comment]
Same for me!

**Comment by faceleg** [comment]
Closing in favour of keeping conversation in #305
