### ISSUE TITLE
Grunt wiredep doesn't inject ngDialog from Bower

### ISSUE THREAD

**Issue by julienpa** [likeastore/ngDialog#157]
The **wiredep** module of Grunt is supposed to scan the bower_component directory of a project and automatically inject dependencies founds within it in index.html file, using bower.json to get the necessary filenames.
I use Yeoman Angular Generator and so far it worked fine with every dependencies I used (normalize.css, font-awesome, velocityjs..etc) but I can't get it to find ngDialog dependency. The bower.json file seems ok but I'm not sure. It is said that the **wiredep** should always work if this file is correctly set up:
> This works if the package author has followed the Bower spec. If the files are not automatically added to your source code, check with the package's repo for support and/or file an issue with them to have it updated.

Any chance the ngDialog repo can be updated to thoroughly follow *Bower spec*?
Thanks!

**Comment by voronianski** [comment]
@julienpa ngDialog strictly follows Bower spec, please check [bower.json](https://github.com/likeastore/ngDialog/blob/master/bower.json) and the original spec [here](https://github.com/bower/bower.json-spec).

Any chance that your didn't setup your environment properly?

**Comment by julienpa** [comment]
@voronianski thanks for the reply. Yes I already had checked the bower.json, but wasn't sure if it was strictly following the spec.
My environment was automatically generated by Yeoman so it should work well, but it can also have a bug. It's just weird because this very environment worked fine with other Bower packages...
I found nothing on the internet related to a possible problem between Yeoman's grunt configuration and ngDialog. Will search more and, in the end, manage to add ngDialog manually!
Thanks again for your time.

**Comment by julienpa** [comment]
The only possible explanation I see right now is that ngDialog is the only package I have which hasn't a lowercased name.
Maybe this makes Grunt's wiredep module to miss it.

**Comment by voronianski** [comment]
@julienpa yeah, that might the reason..

**Comment by julienpa** [comment]
Tried to rename ngDialog to **ngdialog** in bower.json package file, in bower.json project file and also the ngDialog folder, and the wiredep injection **worked**!
So that was causing the problem. Might be a useful workaround for others having the same issue.
Thanks for your replies @voronianski :)

**Comment by voronianski** [comment]
@julienpa great! sadly that modern restrictions do not take into consideration previous spec..

**Comment by julienpa** [comment]
@voronianski actually, I updated all my softwares (especially Bower, npm, and the angular version I use from 1.3.8 to 1.3.9) and it now works without altering any setting (with initial bower.json and ngDialog values..etc). I don't really see exactly which manipulation fixed the problem, but it is now fully functional even without workaround. Really nice! :+1:
