### ISSUE TITLE
cant close modal

### ISSUE THREAD

**Issue by nousacademy** [likeastore/ngDialog#158]
In one controller I have this:

    $scope.clickToOpen = function () {
                    ngDialog.open({
                        template: 'partials/blank.html',
                        controller: 'myCtrl',
                        showClose: false
                    });

                };

In other controller I have this:

    $scope.closeSecond = function () {
        
            ngDialog.close();
        };

I'm able to open the modal etc. but I can't close it! what am i doing wrong??

**Comment by nousacademy** [comment]
I included all the necessary css files this thing wont close! help??

**Comment by voronianski** [comment]
@nousacademy it's in the docs, several ways - 

- save dialog as variable

```javascript
var dialog = ngDialog.open({
   template: 'partials/blank.html',
   controller: 'myCtrl',
   showClose: false
});

dialog.close();
```
- close it with `.close(id)` method - https://github.com/likeastore/ngDialog#closeid-value
- close all - https://github.com/likeastore/ngDialog#closeallvalue

**Comment by nousacademy** [comment]
thanks I got it working finally, awesome library btw!
