### ISSUE TITLE
Option to disable animation and hidden overflow on body

### ISSUE THREAD

**Issue by brunomperes** [likeastore/ngDialog#159]
Would be useful to have an option to disable the animation when the modal is opening and closing

**Comment by letmein** [comment]
+1
would be happy to have this feature

**Comment by kovpack** [comment]
+1 
Waiting for this feature.

**Comment by elhigu** [comment]
One could already "disable" animations by setting animation speed really fast:
```
.ngdialog * {
  -webkit-animation-duration: 0.01s !important;
  -moz-animation-duration: 0.01s !important;
  -o-animation-duration: 0.01s !important;
  -ms-animation-duration: 0.01s !important;
  animation-duration: 0.01s !important;
}
```

But yeah +1 to have it as a feature :)

**Comment by egor-smirnov** [comment]
Added to the list of upcoming features.

**Comment by egor-smirnov** [comment]
Now on master branch. Use new option called "disableAnimation". Docs are here - https://github.com/likeastore/ngDialog#disableanimation-boolean

**Comment by eduardonunesptoptal** [comment]
:+1:
