### ISSUE TITLE
templateCache trouble

### ISSUE THREAD

**Issue by masimplo** [likeastore/ngDialog#16]
Hi there, 

in my scenario I have a login form open both as a dialog and as a full page as well. Both are using the same html template file. During some playing around I noticed that if I opened the dialog after I had visited the full page version, the dialog was not displayed (although background was filled). With some debugging I found out that although you are requesting the template from $templateCache service, you never actually put it there. After getting the template from $http I think you should store it, otherwise don't use $templateCache service at all since you are using the cached $http

**Comment by blazkovicz** [comment]
NgDialog version 0.3.12 now has troubles in same scenario: ngDialog expects string template from $templateCache but $templateCache.get(tmpl) returns array [200, templateString, requestObject, 'OK'].
