### ISSUE TITLE
Problem with ESC option

### ISSUE THREAD

**Issue by suriyagp** [likeastore/ngDialog#160]
i made the ESC option as false, but if i press the ESC the modal again created and overlaps the other in infinite manner.
how to solve this????

**Comment by richardszalay** [comment]
@suriyagp I'm not sure why ESC would initial a new dialog (are you opening one in your callback?)

Alternatively, try using #166 (or change your bower dependency to https://github.com/richardszalay/ngDialog.git#master) as it has some changes around how keys are handled.

**Comment by voronianski** [comment]
@suriyagp should be fixed in `0.4.0`.

**Comment by suriyagp** [comment]
ok i will check
