### ISSUE TITLE
Press enter key open the modal twice

### ISSUE THREAD

**Issue by octavioamu** [likeastore/ngDialog#164]
When enter key is pressed is opening 2 times the same modal. Didn't find any issue related.

**Comment by NicuMotoc** [comment]
I have a similar problem. I click a button that opens the ngDialog after which every time I press enter it opens another ngDialog (which makes the browser window go a bit darker every time. Press enough enter keys and you get a black window with the same ngDialog opened on it again and again in the same position). I should mention that all my <button> tags have type="button".

**Comment by octavioamu** [comment]
@NicuMotoc that is related to #154 , is a focus problem. The second dialog opens on enter because your  focus is in the button you already pressed and didn't change to the dialog.

**Comment by richardszalay** [comment]
I think this will be fixed in #166
