### ISSUE TITLE
does not work with webpack

### ISSUE THREAD

**Issue by thetutlage** [likeastore/ngDialog#167]
#144 

It is still broken , refer to this thread
http://stackoverflow.com/questions/26229323/webpack-and-modernizr-causes-typeerror-document-is-undefined-error

**Comment by voronianski** [comment]
@thetutlage is this related to ngDialog itself?

**Comment by thetutlage** [comment]
Yes , a simple change can fix it, by requiring angular out of the factory function .

```javascript
try { angular = require('angular'); } catch (e) {}
module.exports = factory(angular);
```

**Comment by voronianski** [comment]
@thetutlage but that's the problem of angular not ngDialog..

**Comment by thetutlage** [comment]
The problem is not with angular , the problem is by default `Browserify` and `webpack` looks for module inside `node_modules` and people using bower have angular inside `bower_components` , so my moving the `require('angular')` block outside the factory function will give u a chance to use global copy of angular if there

**Comment by voronianski** [comment]
@thetutlage sorry, I really don't like this approach, it looks like a dirty hack which is not UMD compatible.. you should install angular with `npm` if you're `Browserify` user.

**Comment by Kuraturpa** [comment]
I have this same issue when I'm using Browserify and loading angular from cdn.

**Comment by jecede** [comment]
I know this issue is closed but there is a proper way to fix this:
The names in package.json and ngDialog.js line 17 don't match. Here the module is defined as ngDialog, and in package.json as ng-dialog. So loaders like webpack get confused.
Editing ngDialog into ng-dialog on line 17 fixes this issue.
