### ISSUE TITLE
scope variable is "global"

### ISSUE THREAD

**Issue by joachimgit** [likeastore/ngDialog#170]
Your scope variable is global to the module and reassigned on each .open().
This causes all sorts of bugs when multiple dialogs are opened as the close process tries to cleanup on the wrong scope.

**Comment by voronianski** [comment]
@PeterCrona1989 please take a look on this issue, your pull-request https://github.com/likeastore/ngDialog/pull/141 introduced global `scope` variable (e.g. https://github.com/likeastore/ngDialog/commit/0f398c8d1d599f0c023ed0319cb56e5e84586959#diff-500e1692ffa463397a98a274c90a2263R29)

**Comment by richardszalay** [comment]
This has been resolved in #204
