### ISSUE TITLE
Can I use bootstrap styles

### ISSUE THREAD

**Issue by campa** [likeastore/ngDialog#172]
Hi,

I like your ngDialog becouse of the quality, but I'm not able to use bootstrap styles for the Modal.
Is it possible/easy ? 

here my template: 

```
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->  

```
Thanks
Stefano

**Comment by voronianski** [comment]
@campa it should be possible.. what's exactly the problem? Did you include necessary styles?

**Comment by campa** [comment]
Now, I moved to "dwmkerr/angular-modal-service" because I needed to deliver the project. 

I prefer your ngDialog for a lot of reasons, but I remember that also having standard bootstrap css included I was not able to see it working out of box.

Next days I'll try to return back to ngDialog, do you know if there is a working example of ngDialog  using bootstrap modals I can observe ?

**Comment by voronianski** [comment]
@campa sorry I don't have such example, please provide a demo or fiddle to see what's the problem. You didn't provide any reasonable description of your issue and I'm 99,9% sure that's not the case of ngDialog itself. It can be styled with CSS easily and it doesn't make any dynamic styling.

**Comment by campa** [comment]
You are right. When I a return on it, I'll put a fiddle.
Thank you in advance.

**Comment by mk-lviv** [comment]
It works for me

**Comment by Sylox** [comment]
Have a look at this fork https://github.com/sl0ki/ngBootstrapDialog
