### ISSUE TITLE
Uncaught TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by Sivanthi** [likeastore/ngDialog#177]
using this with requirejs gives Uncaught TypeError: Cannot read property 'module' of undefined. any help

**Comment by Sivanthi** [comment]
it worked when i add following lines to shim config.
 angular: {
		    exports: "angular"
		}

**Comment by jetwaves** [comment]
It works for me too. thanks a lot   (｡･∀･)ﾉﾞ
