### ISSUE TITLE
$escape notification is not propagated correctly

### ISSUE THREAD

**Issue by DorianGrey** [likeastore/ngDialog#179]
My team recently faced an issue regarding the propagation of '$escape' as value-parameter of the object handled over to a dialog's closePromise.

After a small debugging round, we've that publicMethods.close is only called with '$escape' as parameter, but it awaits an id as the first parameter. 
```
close: function (id, value) {
  var $dialog = $el(document.getElementById(id));
  if ($dialog.length) {
    privateMethods.closeDialog($dialog, value);
  } else {
    publicMethods.closeAll(value);
  }
  return publicMethods;
}
```
As a result, the value parameter of this function is undefined, which is propagated.
The cause of this issue seems to be that the onDocumentKeydown function does not have access to the dialog's id. This makes sense somehow, since it's a general function - however, to propagate the signal correctly, it required access to it.
We've fixed this (temporarily) by binding $dialog to the function that is registered to the keydown event.
```
--- public/lib/ngDialog/js/ngDialog.js  (date 1425456746000)
+++ public/lib/ngDialog/js/ngDialog.js  (revision )
@@ -62,9 +62,9 @@
         }
 
         var privateMethods = {
-          onDocumentKeydown: function (event) {
+          onDocumentKeydown: function ($dialog, event) {
             if (event.keyCode === 27) {
-              publicMethods.close('$escape');
+              publicMethods.close($dialog.attr('id'), '$escape');
             }
           },
 
@@ -278,7 +278,7 @@
               });
 
               if (options.closeByEscape) {
-                $body.bind('keydown', privateMethods.onDocumentKeydown);
+                $body.bind('keydown', privateMethods.onDocumentKeydown.bind(this, $dialog));
               }
 
               if (options.closeByNavigation) {
```
Note that only binding the dialog's id should also be sufficient in most cases.

**Comment by DorianGrey** [comment]
Sorry for the delay ... I've re-tested this issue against 0.5.5, and it works fine. 

I've taken a look at the source - you've rewritten publicMethos.close in a way that selects the corresponding dialog, which was not present in the version that this issue refers to.

I.e. - issue is fixed.

**Comment by faceleg** [comment]
Accidental bug fixes are so much better than accidental bugs. 

Thank you very much for coming back and letting us know!
