### ISSUE TITLE
Tries to open script template externally

### ISSUE THREAD

**Issue by theninthnode** [likeastore/ngDialog#183]
I'm trying to open a dialog from a ng-template but it's trying to open it externally. I've pretty much copied the example on the README:

On my html file:

```
<script type="text/ng-template" id="template_<% log._id.toString() %>">
    hello just testing.
</script>
```

In my controller:

```
$scope.openDiffView = function (id) {
        ngDialog.open({ template: 'template_' + id});
};
````

It tries to open externally:

`http://localhost:3002/db/54f7719aaad0da695f5cc839/template_54f8bd1cd4b8c4a74f5e349c 404 (Not Found)`

Have I missed something?

**Comment by sunhk25** [comment]
hi, i have the same problem as you described.
here is demo >> http://jsfiddle.net/akgdxhd0/25/

**Comment by ptlu** [comment]
Same problem here, have you guys found any workarounds?

**Comment by egor-smirnov** [comment]
@theninthnode does issue persist after applying what @ptlu wrote?

**Comment by egor-smirnov** [comment]
Looks like an issue with Angular parsing of dynamic `id` attribute for `script` tag.

Maybe there is some workaround, but it's definitely not connected with ngDialog itself.

**Comment by edgexie** [comment]
@ptlu it's right. you rock . thx
