### ISSUE TITLE
problem to change root scope model value upon ng dialog close

### ISSUE THREAD

**Issue by smart987** [likeastore/ngDialog#185]
I am trying to change my root scope model value upon ng dialog close but the value is remaining as it is. I am expecting $rootScope.isNgDiagClosed to be 'true' when I click 'Show More' button and click close button in ng Dialog. But $rootScope.isNgDiagClosed always remaining false. Can any one help me to fix this? please find plnkr at http://plnkr.co/edit/5Z39jz0q6q2RXPPhiX8Z?p=preview

**Comment by egor-smirnov** [comment]
According to what I see in this plunker everything works as it should. `$rootScope.isNgDiagClosed` is equal to true after closing of dialog.
