### ISSUE TITLE
Using ngDialog with browserify?

### ISSUE THREAD

**Issue by poorgeek** [likeastore/ngDialog#187]
I'm trying to use ngDialog in an app with browserify. I've installed the module via npm, but when I `require ('ng-dialog');` in my app.js I get a `TypeError: undefined is not a function` on ngDialog.js:21. Given that ngDialog is already making allowances for CommonJS, I don't see why I'd need to add browserify-shim, but that's what others receiving a similar error are reporting. Is there something I'm missing other than the shim that I haven't needed with other ng modules until now?

**Comment by voronianski** [comment]
@poorgeek it's not ngDialog issue but Angular's, check:

- https://github.com/angular/angular.js/issues/9699
- http://stackoverflow.com/questions/26452359/updated-to-angular-1-3-0-no-longer-working

**Comment by poorgeek** [comment]
Thanks for those links. I read through the SO article last night, but never saw the angular issue which also linked to an with a PR that explained what was going on. 

I ended up adding browserify-shim with the config from the angular.js issue listed above and ngDialog is working now.
