### ISSUE TITLE
Close when click anywhere else

### ISSUE THREAD

**Issue by corneadoug** [likeastore/ngDialog#197]
Hi,
I just realized that option **closeByDocument** was not working when **overlay:false** was activated.

The main reason being this code

```
if (isOverlay || isCloseBtn) {
  publicMethods.close($dialog.attr('id'), isCloseBtn ? '$closeButton' : '$document');
}
```

In the `closeByDocumentHandler` function.

I made a small modification in local, but it's not working too well if we don't set a fixed size for the dialog.
(I'm using API)

```
closeByDocumentHandler = function (event) {
         var isOverlay = options.closeByDocument ? $el(event.target).hasClass('ngdialog-overlay') : false;
         var isCloseBtn = $el(event.target).hasClass('ngdialog-close');
         var isDialog = $el(event.target).closest('.ngdialog').length >= 1 ? true : false;

        if (isCloseBtn || !isDialog) {
           publicMethods.close($dialog.attr('id'), isCloseBtn ? '$closeButton' : '$document');
        }
 };
```

Is there other way to obtain that kind of result?

Thanks

**Comment by forwardadvance** [comment]
If you need this, the way to do it is to detect a click on the body, then check to make sure the target is not an ancestor of the dialog. This will fire if the click is on anything other than the dialog. Something like this:
 
    var link = function (scope, el) {
     var clickOutside = function (e) {
        if (!el[0].contains(e.target)) {
          // Hide dialog here
        }
      };
      var body = angular.element(document.body);
      body.on('click', clickOutside);
    }
