### ISSUE TITLE
Does ngDialog support validating form inputs?

### ISSUE THREAD

**Issue by nmarshall23** [likeastore/ngDialog#200]
I am looking at validating an input form in a ngDialog. 
I can't get ngMessage to display errors. Any suggestions?

**Comment by egor-smirnov** [comment]
@nmarshall23 Provide some plunker / jsfiddle / whatever please. It would be much easier to experiment if you could do this.

**Comment by egor-smirnov** [comment]
ping @nmarshall23 , please provide some plunker :)

**Comment by nmarshall23** [comment]
You can close this issue, I had incomplete understanding of how to use ngForm. I was looking to see if anyone else had tried to use ngDialog in this way.

I was confused as to how the ngForm's controller binds to the ngDialog. Once $scope is injected into the dialog's controller it's easy to check the ngForm's state.

What I did is when the user clicks to submit the form, I first check the ngForm's validation and if that is good, then call closeThisDialog(). 

If my schedule opens up, I will create an example.

**Comment by egor-smirnov** [comment]
Ok, thank you for update.

**Comment by deadmann** [comment]
i have same issue, i used required on my input box normally, but when i moved my page inside dialog, it bypass all validation, and call the click event
