### ISSUE TITLE
Open ngDialog with url

### ISSUE THREAD

**Issue by bonbon1702** [likeastore/ngDialog#201]
Hi,
Is there anyway to inject url, when i open ngDialog ?
i mean like facebook, when u click a post, a dialog show up with url on top.

**Comment by jpudysz** [comment]
I have one idea, you can do sth like that:
- on modal show you can invoke function: history.pushState(stateObj, "page 2", "bar.html");
(mdn ref: https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history)
Be aware of browser support for this feature: http://caniuse.com/#search=pushstate

**Comment by egor-smirnov** [comment]
@bonbon1702 You could just use `template` parameter of ngDialog documented here - https://github.com/likeastore/ngDialog#template-string

This should work as we use $http service internally to load template (refer to https://github.com/likeastore/ngDialog/blob/88c030f4827766831baca6980ed26a79f4e306a2/js/ngDialog.js). The only reason why it won't load could be CORS limitations (http://enable-cors.org/), but CORS is nothing to do with ngDialog itself.
