### ISSUE TITLE
Opening a dialog immediately after `closeAll()` destroys the wrong scope

### ISSUE THREAD

**Issue by richardszalay** [likeastore/ngDialog#202]
If you invoke `closeAll()` and then immediately open a new dialog, any calls to `closeThisDialog` on the new dialog won't work.

The root cause of that the `scope` variable in ngDialog is scoped to the entire component and therefore essentially "global" state (between dialog instances). Since scope can be retrieved from `element.scope()`, it would make much more sense to localise the (js) scope of the (angular) scope variable.

PR incoming.

**Comment by egor-smirnov** [comment]
Fixed in PR.
