### ISSUE TITLE
Disabling scroll when dialog is open

### ISSUE THREAD

**Issue by jerepaajanen** [likeastore/ngDialog#206]
Is it possible to disable scrolling when dialog is open? Overflow: hidden in body doesn't work because I'm using front-end framework that has overflow-y: scroll in html-tag.

**Comment by westonganger** [comment]
+1

**Comment by HarrisRobin** [comment]
Why would you have overflow-y scroll in html tag? Can't you just remove it. You won't be able to achieve what you need if the html tag is forcing the scroll. Perhaps you can dynamically modify the html tag when the dialog is open by either changing the attribute or some class with !important at the end.

**Comment by egor-smirnov** [comment]
@jerepaajanen I think it could be a bit unexpected for users if we apply what you propose by default (maybe users still want to have scrolling of body when they open the dialog). For me, it looks like this functionality could be implemented as an optional parameter which is by default false.

Your thoughts?

**Comment by jerepaajanen** [comment]
As a optional parameter that could be really nice. When html/body scroll isn't disabled, it is kinda troublesome to scroll a bit longer dialogs especially when viewing in small screes or mobile. Only background site is scrolled, not the actual dialog.

**Comment by egor-smirnov** [comment]
Ok, then added to the features list for future releases.

**Comment by johnc1984** [comment]
Hi just wondering when this might be going live? As without it ngDialog really doesn't work well on long pages and often locks up.

**Comment by jerepaajanen** [comment]
When this is going to live?

**Comment by egor-smirnov** [comment]
@jerepaajanen After some diving into source code I noticed that we already have CSS class `ngdialog-open` which is added to `body` tag and has `overflow: hidden`. Will it be enough for your case if we'll just add the same class to `html` tag? If I understand correctly, this is what you need.

**Comment by johncarmichael** [comment]
@egor-smirnov That would work perfectly.

**Comment by jerepaajanen** [comment]
@egor-smirnov Sounds great!

**Comment by marmotz** [comment]
:+1:

**Comment by davidvuong** [comment]
@marmotz +1 looks pretty good!

There's a bit of code duplication with how you're adding/removing the `ng-dialog` class and the initialization of the state/location change listeners but it's fairly minimal. Can I ask that you also update the README.md to document this new `forceHTMLReload` function?

@egor-smirnov What do you think?

**Comment by marmotz** [comment]
@davidvuong I've updated README.md file.

**Comment by marmotz** [comment]
@davidvuong Here is a little refactoring following your advice.

**Comment by egor-smirnov** [comment]
@davidvuong @marmotz let's move discussion to https://github.com/likeastore/ngDialog/pull/280

**Comment by roaks3** [comment]
This has the unfortunate side effect of bumping the user up to the top of a long page whenever a dialog is opened.  The previous functionality opened the dialog in-place, which feels more natural to me, but will also probably surprise some people when upgrading.  I'm not sure there's an ideal solution (open in-place AND disable scrolling), but this change can be overridden in the project CSS to match the old behavior:
```
html.ngdialog-open {
  overflow: visible;
}
```

**Comment by jmkenz** [comment]
To avoid bumping the user up to the top of the page when opening a modal, the script needs to take note of the current scroll position first and save it to a variable. Then the <html> can be set to overflow:hidden, and the scroll position variable can be used to set a negative margin-top on the <html>.  That will simulate the scroll position the user was at before opening the modal.  When closing the modal, that margin-top on the <html> will then need to be removed.
