### ISSUE TITLE
Problem with angular-animate on version 1.4.0-rc.0

### ISSUE THREAD

**Issue by jonagoldman** [likeastore/ngDialog#211]
I know is still a release candidate but I am getting this error:

![image](https://cloud.githubusercontent.com/assets/1297559/7105894/a20303c6-e137-11e4-81b1-69626c5ae390.png)

Using angular 1.4.0-rc.0 and angular-animate 1.4.0-rc.0

**Comment by tsanko** [comment]
+1

**Comment by hippee-lee** [comment]
+1.
I work with @tsanko and we had to revert back to Angular 1.3 to address the bug.

**Comment by Cornally** [comment]
I'm seeing this as well.  See the breaking changes here: https://github.com/angular/angular.js/commit/c8700f04fb6fb5dc21ac24de8665c0476d6db5ef

**Comment by egor-smirnov** [comment]
I've added Angular 1.4.0 + Angular Animate 1.4.0 to the loaded scripts and didn't notice any errors. Maybe I am doing something wrong?

@jonagoldman, @tsanko, @hippee-lee, @Cornally Do you still have this issue with stable releases of AngularJS 1.4?

**Comment by jonagoldman** [comment]
I have another problem where modal.close() does not close the dialog in 1.4 but I need to check that out and get back to you.

**Comment by egor-smirnov** [comment]
@jonagoldman thing with modal.close() should be fixed in latest master. Could you please confirm?

**Comment by jonagoldman** [comment]
@egor-smirnov: I'll to that, thanks. Regarding the original error, I am not longer getting it with 1.4 so I guess this issue can be closed.
