### ISSUE TITLE
Add ability to "attach"/position a modal in relation to another element

### ISSUE THREAD

**Issue by NateRedding** [likeastore/ngDialog#212]
I am in a position where I need to attach a modal in relation to another element, as in the following screenshot:

![attached-modal](https://cloud.githubusercontent.com/assets/3064840/7125607/67c22b78-e200-11e4-8213-09200799984c.png)

My proposal is to add a few options to allow this to be done:

'attachTo' - string selector for the element to attach to.
'attachSide' - The side of the element to which the modal should be attached. One of: 'bottom' (default), 'top', 'left', 'right'. 
'attachAlignment' - The side of the modal that should line up with the corresponding side of the element to which it is attached. For instance, in the image, the modal is aligned to the right side of the element. If attached to the 'left' or 'right' sides, possible options would be 'top', 'middle' (default), 'bottom'. If attached to the 'top' or 'bottom' sides, possible options would be 'left', 'center' (default), 'right'.

I was able to make this work with ngDialog and a bit of hacking... it would be pretty sweet if it were an official option.

**Comment by tastycode** [comment]
Tether might work better for this. https://github.com/HubSpot/tether/.

You could do the popover without the "modal" part. It seems trivial to use a global overlay and some css tricks to get the darkened background.

Also, this is similar and mike work better for you. http://scruffles.github.io/BootstrapModalPopover/
