### ISSUE TITLE
ngDialog can't find body

### ISSUE THREAD

**Issue by TylerPflueger** [likeastore/ngDialog#218]
I currently have a setup that a ui-view attribute is on the body tag. I call the dialog right about start up but it doesn't display the dialog. I'm guessing its unable to find the body tag because of the ui-view. Is there any way to update so it can find the body tag?

**Comment by payk** [comment]
I have the exact same issue. 
you can get arround it by passing the "appendTo" argument with a string selector "body"

on this way it wont use its internalt $body reference.

i am guessing this part is not working:

                var $body = $document.find('body');
                if (forceBodyReload) {
                    $rootScope.$on('$locationChangeSuccess', function () {
                        $body = $document.find('body');
                    });
                }

**Comment by egor-smirnov** [comment]
@TylerPflueger Could you please provide plunker / jsfiddle with your specific example?

**Comment by egor-smirnov** [comment]
Could you also try to use https://github.com/likeastore/ngDialog#setforcebodyreloadboolean?

**Comment by payk** [comment]
its not specific. it fails as long the ui-view argument is on the body tag. 

this tag will be replaced on route change, and its internal reference wont be pointing to a dom object anymore. 

forcereload should just work as well as providing a appendTo-selector (to the body in that case)

**Comment by TylerPflueger** [comment]
@egor-smirnov Sorry, I completely forgot about this issue since it was just for a school project. In the project the user would check on initialization if they are signed in or not, otherwise it would go to the home screen and display the modal for login. Here is an example: http://plnkr.co/edit/5aXhXe6L8mAtyjaH3xZz?p=preview#.VY76kRMnepw.link

I tried to use setForceBodyReload but I would get errors since its not on the object.

**Comment by payk** [comment]
@TylerPflueger: try my solution with the body selector. it worked for me perfectly.
