### ISSUE TITLE
Can't pass data into controller

### ISSUE THREAD

**Issue by amcclung** [likeastore/ngDialog#227]
Hi,

I'm having trouble getting data into a controller even in my basic demo. Here's what I've got in my main controller:

    ngDialog.open({ 
        template: 'test.html',
        controller: "TestController",
        data: {test:"Hello from the main application."},
    });

My dialog's controller is this:

    var TestController = angular.module('TestController', []);
    TestController.controller('TestController',
        function($scope)
        {
            // This generates a console error because it can't read .test of
            // undefined (scope.parent.ngDialogData is undefined)
            $scope.test = $scope.$parent.ngDialogData.test;
        }
    );

What am I doing wrong?

**Comment by MiguelMike** [comment]
You should use: `$scope.test = $scope.ngDialogData.test;` No `$parent` in between.

**Comment by egor-smirnov** [comment]
@amcclung did not using of $parent help you?

**Comment by alxvallejo** [comment]
I still get ngDialogData is not defined.

**Comment by faceleg** [comment]
Have you tried using `resolve`? That is what I use to get data into the controller.

e.g: 

```JS
ngDialog.open({ 
    template: 'test.html',
    controller: "TestController",
    resolve: {
        test: function() {
            return "Hello from the main application."
        }
    }
});

var TestController = angular.module('TestController', []);
TestController.controller('TestController',
    function($scope, test)
    {
        // This generates a console error because it can't read .test of
        // undefined (scope.parent.ngDialogData is undefined)
        $scope.test = test;
    }
);
```

If you ever find yourself using `$parent`, stop doing it and look for a better way. I'm not saying this to be nasty, I'm trying to help - I can't tell you how many hours I've wasted debugging issues caused by myself (and others) using this.

**Comment by MiguelMike** [comment]
@alxvallejo Could you share your code? Or is it the same as the code on top of this issue?

**Comment by alxvallejo** [comment]
@faceleg Thanks. I eventually got it to work using ControllerAs 'vm':

```
    ngDialog.openConfirm({ 
            template: '/components/dialogs/delete-dialog.html',
            controller: 'DeleteDialogController',
            controllerAs: 'vm',
            resolve: { item: function() {
                return team; 
            } }
        }).then(function() {
            vm.teamDelete(team);
        });
```

**Comment by faceleg** [comment]
wait so `vm.team` was populated on your dialog's controller?

**Comment by alxvallejo** [comment]
I'm passing the resolve param to my controller:

```
angular
	.module('stateApp')
	.controller('DeleteDialogController', DeleteDialogController);

function DeleteDialogController(item) {
	var vm = this;
	vm.item = item;
}
```

**Comment by faceleg** [comment]
right thought so. thanks for getting back to me
