### ISSUE TITLE
When closing dialog i'm getting an error : Cannot read property '$$nextSibling' of null 

### ISSUE THREAD

**Issue by boban984** [likeastore/ngDialog#228]
The error is caused by this code

scope.$destroy();

Wrapping the call in a $timeout function solves the issue

$timeout(function () { scope.$destroy(); }, 0);

**Comment by egor-smirnov** [comment]
Could you provide example (using service like plunkr) where issue happens?

Without having this it would be hard to find the reason.

**Comment by egor-smirnov** [comment]
ping @boban984 , prepare plunker please :)

**Comment by egor-smirnov** [comment]
No response for more than a month. Assuming that issue is resolved.

Feel free to reopen if you still have the issue.

**Comment by boban984** [comment]
Hi Egor 

I was having the issue when i disabled debug info and calling destroy on one of my custom directives that used ngDialog.

I solved the issue by using timeout as seen above
