### ISSUE TITLE
When a template is opened, it's rendered multiple times

### ISSUE THREAD

**Issue by barmatt** [likeastore/ngDialog#229]
Hi,

When I open a ngDialog, the template is rendered multiple times. So if I bind an angular function in my template the function is also called many times...

For example:
In a first angular controller:
```javascript
ngDialog.open({
    template: 'test.html',
   controller:'testController'
});
```

the template:
```html
<div>Hello {{count()}}<div>
```

Into the controller:
```javascript
var a = 0;
$scope.count = function(){
    console.log(a);
};
```

**Comment by FaynePerera** [comment]
Yeah, i have the same problem, i've tried disabling template caching but t does the same thing.

**Comment by egor-smirnov** [comment]
What you are posted here is default Angular behaviour. You are using your `count()` method inside the template and it happens that Angular re-evaluates binded expression multiple times.

You could find more information here - http://thenittygritty.co/angularjs-pitfalls-using-scopes and http://stackoverflow.com/questions/20417407/why-ng-class-is-called-several-times-in-directive-of-angular.

So, this is not ngDialog related issue thus I am closing an issue.
