### ISSUE TITLE
Loading state for URL templates

### ISSUE THREAD

**Issue by simon-whitehead** [likeastore/ngDialog#231]
Hi there,

Just wondering if there is any way I can plug in to this to show a "Loading" state when the template is loading via a GET request?

Currently if our server(s) are under high load or the client connection speed is less than optimal it might take ~3-4 seconds for the template to resolve and the dialog to show. Can we show the dialog with a loading spinner or something somehow?

I am looking into how I might edit the lib now to allow for this - but if someone has an idea that would be great.

Cheers,

Simon

**Comment by egor-smirnov** [comment]
@simon-whitehead What about adding your templates into $templateCache (you could use plugin like https://www.npmjs.com/package/gulp-ng-html2js to automate this)? Will this work for you? In that case you won't need to add loading state at all.

Also you could use solutions like https://github.com/chieffancypants/angular-loading-bar / https://github.com/wongatech/angular-http-loader, but they are likely to be more 'global' ones.

**Comment by egor-smirnov** [comment]
@simon-whitehead I've introduced two new events - `ngDialog.templateLoading` and `ngDialog.templateLoaded`. You could use them to show / hide your loader.
