### ISSUE TITLE
Dialog together with ui-route

### ISSUE THREAD

**Issue by abelan** [likeastore/ngDialog#233]
I would like to get possibility to use route in the dialog. E.g.
state definition
$stateProvider.state('login', {url: '/login', templateUrl: 'pages/login.html'});
usage
<_a ui-sref="login">Login</_a>
<_a href="login" ng-dialog-ui-sref="login">Login in popup</_a>

Or maybe I can do it in other way?

**Comment by jonagoldman** [comment]
its not clear what you are trying to do

**Comment by abelan** [comment]
I'm trying to show login form either on the page or in the dialog.
So I have a route ('login') and e.g. two links
<_a ui-sref="login">Login</_a>
<_a ng-dialog-sref="login">Popup login</_a>
The first shows the form inside <div ui-view></div> and the second should open popup with that form

**Comment by jonagoldman** [comment]
It seems an issue not related directly with ngDialog but with the routing you are using.
I dont know what is that "ng-dialog-sref" thing, but in general you need a route called "login" and inside that route you have an if/else statement to show a popup or a regular page with a form.

**Comment by abelan** [comment]
Actually it's an enhancement and not a bug in ngDialog. 
"ng-dialog-sref" is just an example of possible directive (similar to 'ui-sref) that contains a state of route.
<_a ui-sref="login" ng-dialog-sref="login" ng-dialog-active="isNotLoginPage()">Login</_a>
So my goal is to have something like this link that will open a dialog for non-login pages or show the form directly on page.
'ng-dialog-active' (please see <a href="https://github.com/likeastore/ngDialog/issues/181">#181</a>)

P.S. I'm a new in angular so probably I don't understand everything you are trying to explain.
And if you can show me an example with 'if' condition in the route I'll be grateful to you.

**Comment by egor-smirnov** [comment]
@abelan there is standard way to do such a things via ui-router - https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state. Their example uses modal dialog from ui-bootstrap. For ngDialog you will have code like:

```javascript
$stateProvider.state("some.route", {
    url: "/some-route",
    onEnter: ['ngDialog', function(ngDialog) {
        ngDialog.open({
            template: 'templateId'
        }).closePromise.finally(function() {
            // do whatever you want
        });
    }]
});
```

`ngDialog.open(..).closePromise` id documented here - https://github.com/likeastore/ngDialog#closepromise-promise

If you have additional questions, feel free to reopen this issue.
