### ISSUE TITLE
dialog inserting into dom, not overlaying

### ISSUE THREAD

**Issue by jmls** [likeastore/ngDialog#235]
Maybe I'm missng something simple, but I can't seem to get the dialog to overlay the screen - it inserts the html into the dom, pushing everything down

before pushing the dialog button : 

![screenshot from 2015-05-28 17 33 34](https://cloud.githubusercontent.com/assets/929523/7865356/ed7b9632-055f-11e5-8822-767668f4e805.png)

after : 

![screenshot from 2015-05-28 17 33 57](https://cloud.githubusercontent.com/assets/929523/7865367/0245c7c2-0560-11e5-8814-b47a01efc658.png)

as you can see, the "demo" text has been pushed down instead of the dialog overlaying the screen

any clues ? 

thanks !

**Comment by egor-smirnov** [comment]
Did you include required CSS files like described here - https://github.com/likeastore/ngDialog#usage?

**Comment by egor-smirnov** [comment]
ping @jmls

**Comment by AlverthoMartinez** [comment]
I have a similar issue, the overlay isn't appended, just the div element with the class ngdialog,
here is the Plunker...
http://plnkr.co/edit/GICuk3aJDKnFkjy9HdDe?p=preview

**Comment by egor-smirnov** [comment]
No response for more than a month. Assuming that issue is resolved.

Feel free to reopen if you still have this issue.
