### ISSUE TITLE
Add controllerAs and bindToController to ngDialog

### ISSUE THREAD

**Issue by sibeliusseraphini** [likeastore/ngDialog#236]
I think it is a good idea to add controllerAs and bindToController to allow us to follow the Angular Style Guide (https://github.com/johnpapa/angular-styleguide), that uses vm (ViewModel) instead of $scope

**Comment by maxklenk** [comment]
`controllerAs` is supported, even it is not documented.

**Comment by egor-smirnov** [comment]
Going to do it in some time.

**Comment by egor-smirnov** [comment]
Documentation about controllerAs - https://github.com/likeastore/ngDialog#controlleras-string
Documentation about bindToController - https://github.com/likeastore/ngDialog#directive

**Comment by alxvallejo** [comment]
@egor-smirnov Both of these imply that you're creating a new controller specifically for the modal. What if you just want to inherit the parent controller's scope using vm (not $scope) syntax? I've been trying to find a solution there but haven't yet.

**Comment by faceleg** [comment]
@alxvallejo it would be helpful if you could open another issue for the `bindToController` feature request.
