### ISSUE TITLE
Make template accept a css selector

### ISSUE THREAD

**Issue by dodtsair** [likeastore/ngDialog#237]
Would it be possible to make template accept a css selector?  I think this would be better than a server reference because it does not need to be loaded from the server.  Also better than a script reference, I don't know how many editors would recognize the script section as html.  You might not get code completion and highlighting.

**Comment by egor-smirnov** [comment]
@dodtsair I won't introduce such a feature. Using named template is a standard-de-facto Angular solution at the moment. 

There is no need to manually include these script tags into your main HTML file, so IDE should be fine. You could store all your HTML templates separately and generate necessary code in your build script to put them to $templateCache using plugin like this - https://www.npmjs.com/package/gulp-ng-html2js.

**Comment by egor-smirnov** [comment]
I think it could be a good idea to open an issue to document how could we manipulate $templateCache. Thanks @dodtsair
