### ISSUE TITLE
Overwrite defaults for openConfirm

### ISSUE THREAD

**Issue by maxklenk** [likeastore/ngDialog#238]
I use `openConfirm` for my modals to work with both `.then` and `.catch`, but by doing so I always have to overwrite the close triggers.
`closeByDocument` and `closeByEscape` for openConfirm should be able to set in the options.

**Comment by egor-smirnov** [comment]
It's now possible to set `closeByDocument` and `closeByEscape` by using options of `openConfirm`. Feel  free to correct me if I am wrong.
