### ISSUE TITLE
All I get is a gray bar with text on top

### ISSUE THREAD

**Issue by blakemcbride** [likeastore/ngDialog#239]
I am doing:

                            ngDialog.open({
                                plain: true,
                                template: '<p>Message goes here</p>'
                            });

All I get is a gray bar at the top of the window, full width, with the text.  I tried in-line styling but I can't get a popup window.  All I get is a modal gray bar.  How can I shrink the width and center it?

Thanks.

**Comment by voronianski** [comment]
@blakemcbride do you have necessary theme css files included? - https://github.com/likeastore/ngDialog/tree/master/css

**Comment by blakemcbride** [comment]
I have the following in index.html

 <link rel="stylesheet" type="text/css" href="bower_components/ngDialog/css/ngDialog.css">

No file load errors.

Thanks for the help.

Blake

**Comment by chiptus** [comment]
same issue, have all the css

**Comment by egor-smirnov** [comment]
@chiptus PR's better describing this part in documentation are welcome.

**Comment by blakemcbride** [comment]
I still have the problem.  chiptus states "when adding one of the templates - fixed".  I don't know what that means.  Sure appreciate any help!

Thanks.

**Comment by egor-smirnov** [comment]
@blakemcbride could you please reproduce your problem in jsfiddle / jsbin / something else ? Hard to say what's your problem without actually seeing it.

**Comment by egor-smirnov** [comment]
ping @blakemcbride - prepare plunker please :)

**Comment by egor-smirnov** [comment]
No response for a month, assuming that issue is resolved.

Feel free to reopen if you still have the issue.
