### ISSUE TITLE
add method to check for open dialogs

### ISSUE THREAD

**Issue by maxklenk** [likeastore/ngDialog#240]
There is a `.closeAll()` method, but I would like to check first if there are open modals (for example to stop location change and just close the modal).

Something like `.getOpenModals()` which returns the ids of them would be nice.

**Comment by thoughtpalette** [comment]
@maxklenk https://github.com/likeastore/ngDialog#isopenid

There is `isOpen()` which you can perform a conditional on and proceed/halt

**Comment by maxklenk** [comment]
@thoughtpalette thank you for the response, but for using `isOpen()` I have to have to id of the dialog already, which I don't have.

**Comment by egor-smirnov** [comment]
@maxklenk added this to plan.
