### ISSUE TITLE
Using ngDialog.close() doesn't work as expected with Angular 1.4.0

### ISSUE THREAD

**Issue by julienpa** [likeastore/ngDialog#243]
`ngDialog.close()` without arguments is supposed to do the same as `ngDialog.closeAll()`, but since I updated to Angular 1.4, it broke all my calls to close() (not closing opened dialogs).

Maybe this will be fixed when a compatible version will be released? (the dependencies seem to indicate that ngDialog 0.4.0 requires Angular 1.3.15).

**Comment by egor-smirnov** [comment]
Will look at this in the nearest days and let you know how it goes. Seems to be quite important.
