### ISSUE TITLE
Show different themes on Demo

### ISSUE THREAD

**Issue by Jakobovski** [likeastore/ngDialog#245]
Thanks for the Super Awesome project!

It would be great if on the demo page you demonstrated the different themes.

**Comment by egor-smirnov** [comment]
Ok, going to do it at some future, thanks for idea.

**Comment by WalterInSH** [comment]
+1

**Comment by WalterInSH** [comment]
+1

**Comment by egor-smirnov** [comment]
I think I won't do this in any near time, too much other stuff to do.

Feel free to contribute if you would like this to happen. Just open new PR in that case. 

Thank you.
