### ISSUE TITLE
"ui-tinymce" not showing in ngDialog 

### ISSUE THREAD

**Issue by phuyem** [likeastore/ngDialog#247]
Hello,

"ui-tinymce" editor got displayed easily and nicely on main screen/view, but not in ngDialog. I see no error Chrome console. I placed some debug point in both plugin but saw nothing suspicious. 

Thank you for your great plugin!

The plugin is here : https://github.com/angular-ui/ui-tinymce

**Comment by egor-smirnov** [comment]
Could you please prepare plunker / jsbin / something else to reproduce the problem you have?

It would be very helpful in order to tackle your specific problem.

**Comment by egor-smirnov** [comment]
ping @phuyem

**Comment by phuyem** [comment]
Sorry for abandoning the topic like this. I am too busy :(. I got a work around with bootstrap-ui model.. Thanks
