### ISSUE TITLE
Allow an instance of an object to be passed in as the controller option

### ISSUE THREAD

**Issue by RickEyre** [likeastore/ngDialog#249]
Currently one can only pass in the name of the controller to instantiate or the function constructor itself. Rather, I'd like to pass in a controller that has already been instantiated.

Is it possible/would you accept a PR to make this happen?

**Comment by egor-smirnov** [comment]
Could you please be more specific with some code examples? Not necessary to be working code, some kind of pseudo-code should be enough.

For me 'the name of the controller to instantiate' and 'controller that has already been instantiated' is more or less the same applied to Angular world.

**Comment by egor-smirnov** [comment]
I guess all cases were covered by recent pull request https://github.com/likeastore/ngDialog/pull/260.
