### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by voronianski** [likeastore/ngDialog#250]
This library appeared as a small hack to easily provide dialogs/popups inside Angular apps with only dependency on Angular. During time and many efforts of community and [Likeastore](http://likeastore.com) team it became one of the best solutions for dialogs in Angular world. 

For now this project requires more attention and time for new features, support and development but as I'm no longer active in Angular.js development I don't have time for that. So I'm looking for someone(s) to take over maintenance. This would include triaging issues, fixing bugs, reviewing pull requests and releasing new versions. New Angular versions is coming with some breaking changes, so it would also require some development efforts for ngDialog.

Ideally candidate(s) has experience with Angular.js and passion to work with it, knows basic tooling as grunt, karma etc. though build, style and test suites can be adopted easily.

Latest version `0.4.0` was downloaded more than 4k times on NPM last month. There are plenty [interesting things](https://github.com/likeastore/ngDialog/issues) to do yet! :rocket:

**Comment by malixsys** [comment]
I'm using trying to use ngDialog, so I would have a vested interest in maintaining it if it works with Ionic

**Comment by egor-smirnov** [comment]
I am interested. My experience with Angular / grunt / karma etc. should be enough.

As the first shot we should try to resolve as much currently opened issues as possible.

**Comment by voronianski** [comment]
@egor-smirnov @malixsys Awesome! You can observe the issues and maybe you'll have some proposals or cooperate with the guys who raised them. As soon as you will be ready with solving some I'll add you to maintainers team. Thanks!

**Comment by voronianski** [comment]
@egor-smirnov I would like all your (and not yours as well) following changes (e.g. fixing current issues, adding new features) to start with new version `0.5.0`. What do you think? It can be released to npm as soon as some of the issues will be resolved with `rc` or `beta` prefix.

**Comment by voronianski** [comment]
@egor-smirnov I've invited you to maintainers team.

**Comment by egor-smirnov** [comment]
@voronianski it's reasonable to release new functionality under new version. I am ok with that.

Thank you for invitation:) Accepted it.

**Comment by davidvuong** [comment]
Hi @voronianski,

I'm interested. We use ngDialog quite extensively at stitch.net so although I haven't dug into the ngDialog source much (aside from trying to figure out some bizarre weirdness on mobile), I'd be happy to help.

I haven't made any open source contributions yet but where better to start than a highly used 3rd party library! I'm experienced with Angular and the general build tools used in ngDialog so that's not a problem.

**Comment by voronianski** [comment]
@davidvuong hey, thanks! Your help is highly appreciated though @egor-smirnov already started curation of the project. 

I think you, guys, can cooperate together 'cause there are still [issues](https://github.com/likeastore/ngDialog/issues) to do :wink: 

@egor-smirnov As far as I see a lot of good work and fixes were already made by and it looks like we can release the next version with them (`0.5.0`) and focus on other things, thoughts?

**Comment by egor-smirnov** [comment]
@davidvuong Thank you and welcome!

@voronianski 0.5.0 looks good, though I would like these 2 PR's to be reviewed before new release - https://github.com/likeastore/ngDialog/pull/280 and https://github.com/likeastore/ngDialog/pull/279. There is also couple of related issues - https://github.com/likeastore/ngDialog/issues/206 and https://github.com/likeastore/ngDialog/issues/222. I was going to tackle this stuff, but just got ill recently :/ So if @davidvuong could help with all these, it would be just perfect.

@davidvuong Is it possible for you to help with that issues / PR's? Also feel free to work on any other issue you would like. Any help is highly appreciated!

**Comment by davidvuong** [comment]
@voronianski Absolutely! 

@egor-smirnov Sure not a problem. I need to spend a bit of time digging into the ngDialog source so I get a better idea of how everything works but afterwards I'll prioritize those issues first! I'm usually busy on Mondays and Tuesdays (UTC+10) but I'll try my best to make time :+1:

**Comment by egor-smirnov** [comment]
@voronianski could you please send invitation for @davidvuong ?

**Comment by voronianski** [comment]
@egor-smirnov yess

**Comment by voronianski** [comment]
@egor-smirnov done();

**Comment by egor-smirnov** [comment]
@voronianski thank you.

@davidvuong there is absolutely no requirements about time you dedicate. This is an open source project, so there is no expectations. No pressure, no schedule. Enjoy!

**Comment by davidvuong** [comment]
Cheers!

**Comment by faceleg** [comment]
If y'all need another maintainer tap me in

**Comment by egor-smirnov** [comment]
I think we need. I'll be on vacations over the next month, we might need help with increasing numbero f requests.

**Comment by faceleg** [comment]
I'm still keen to help out with this.

**Comment by egor-smirnov** [comment]
Now it's call of @voronianski :)

**Comment by voronianski** [comment]
@egor-smirnov ?

**Comment by voronianski** [comment]
@faceleg invited you to have rights maintain this repo :wink: 

/cc @egor-smirnov

**Comment by faceleg** [comment]
Thanks! What is the general procedure for accepting submissions - e.g. at least two maintainers accepting?

**Comment by faceleg** [comment]
I want to update the contributing document with a section:

## Testing

ngDialog is in use by many people. In order to ensure quality and prevent regressions, all contributions require unit tests proving that the contribution:

1. Fixes a bug
2. Performs new functionality as expected
3. Behaves in a predictable manner when misused (bad input given as an option for example)

In addition, where a contribution is aimed at resolving a bug that occurs only in a browser, an e2e test proving the resolution should be included.

**Comment by egor-smirnov** [comment]
@faceleg seems to me 2 contributors accepting PR should be enough.

About testing etc. - I find your propositions reasonable, thank you. I'll review your PR and other things in about a week when I return back from vacations.

**Comment by faceleg** [comment]
Merged it in, there are outstanding PR that I feel require protractor tests to ensure they work as advertised. Waiting for the owner to open a CircleCI account to switch to that from travis - travis's docker-compose support seems broken

**Comment by faceleg** [comment]
IMHO there are enough chefs in the kitchen now.
