### ISSUE TITLE
how to set dialog width?

### ISSUE THREAD

**Issue by goople8** [likeastore/ngDialog#251]
help me!
how to set dialog width?

this code：

$scope.save = function () {
        ngDialog.open({
            template: '/Member/Media/save_step1.html'
        });
 };

**Comment by egor-smirnov** [comment]
I would say use CSS for this. Currently ngDialog doesn't support setting of width via JavaScript.

Here is relevant line in CSS for default theme - https://github.com/likeastore/ngDialog/blob/master/css/ngDialog-theme-default.css#L84

Just override '.ngdialog.ngdialog-theme-default .ngdialog-content' with width value you would like to have.

P.S. In case you are using another theme, find the corresponding CSS class for your theme.

**Comment by egor-smirnov** [comment]
Here is also example CSS for these purposes - https://github.com/egor-smirnov/ngDialog/blob/master/css/ngDialog-custom-width.css

**Comment by Seiifer** [comment]
I'm not sure what exactly you are looking for but you can change the width of the dialog, for example, I'm doing as follow :
```javascript
// Search pop up
    $scope.openSearchDialog = function () {
        $rootScope.theme = 'ngdialog-theme-plain custom-width';
        ngDialog.open({
            template: 'searchDialog',
            controller: 'InsideCtrl',
            className: 'ngdialog-theme-plain custom-width',
            scope: $scope,
            closeByDocument: false
        });
    };
```

And in the css file :
```css
.ngdialog.ngdialog-theme-plain.custom-width .ngdialog-content {
    width: 42%;
}
```

Obviously, replace 42% with the width you want.

Not sure there is such an option for height though, since I don't think we can scroll inside a dialog at the moment.

**Comment by egor-smirnov** [comment]
Should be understandable enough. Feel free to re-open issue if you have further questions regarding setting of dialog width.
