### ISSUE TITLE
controllerAs error

### ISSUE THREAD

**Issue by djindjic** [likeastore/ngDialog#259]
I have some strange behaviour after setting up controllerAs syntax. Here is a console log:

![screen shot 2015-06-19 at 10 51 31 am](https://cloud.githubusercontent.com/assets/1564068/8250217/dd2eae68-1671-11e5-8b8c-12921edb3e5a.png)

So I have simple code to try this feature:

```js
...
      ctrl.openDialog = function () {
          ngDialog.open({
            template:   'popupTmpl.html',
            controller: [function() {
              var vm = this;
              vm.name = 'child';
            }],
            controllerAs: 'ctrlChild'
          });
        };
...
```

maybe you @andrewogburn know what is a problem?

**Comment by egor-smirnov** [comment]
I guess I know what's the issue. That's maybe because of [] inside controller definition.

@djindjic does it work for you in case of following code?


```javascript
      ctrl.openDialog = function () {
          ngDialog.open({
            template:   'popupTmpl.html',
            controller: function() {
              var vm = this;
              vm.name = 'child';
            },
            controllerAs: 'ctrlChild'
          });
        };
```

This is not a solution as we should correctly handle extra dependencies injected into controller, but just wanted to clarify that issue is because of [].

**Comment by djindjic** [comment]
@egor-smirnov just tried, I've got same issue.

**Comment by egor-smirnov** [comment]
@djindjic could you please prepare plunker where I could play with what you have right now?

**Comment by djindjic** [comment]
Yes, give me just a little time :+1:

**Comment by andrewogburn** [comment]
Thinking through how I implemented it, I think it only supports named
controllers. I don't think it will ever work with an inline controller
definition. I just got to my desk, so I'm looking into it now.

**Comment by andrewogburn** [comment]
Just submitted #260 that should resolve this issue. I confirmed it is working with inline controller definition as well as named controllers in a local project I'm working on.

**Comment by egor-smirnov** [comment]
@andrewogburn thanks, will check it later.

**Comment by djindjic** [comment]
just to confirm that master works with inline controller. thanks guys!
