### ISSUE TITLE
ng-dialog-close-previous not work on Angular 1.2

### ISSUE THREAD

**Issue by Freezko** [likeastore/ngDialog#262]
ng-dialog-close-previous not work on Angular 1.2 (without any error)

If i use ngDialog v 0.3.12, it work.

**Comment by egor-smirnov** [comment]
@Freezko I just tried examples from here - https://github.com/likeastore/ngDialog/tree/master/example and changed Angular version to 1.2.1. Works as it should.

So, I guess we'll need jsfiddle / plunker from you to reproduce this issue.

**Comment by Freezko** [comment]
http://embed.plnkr.co/lJWH6BWTJNUiKAEHXsaL/preview

**Comment by egor-smirnov** [comment]
Please use the latest version of JavaScript from master where `ng-dialog-close-previous` works. See this plunker which is the same as yours, but includes JS file from master - http://plnkr.co/edit/cTJX5epN2zzhk5v59L7J?p=preview

Sorry for inconvenience, I believe this would be solved when we'll have new release.
