### ISSUE TITLE
close by document not work

### ISSUE THREAD

**Issue by Freezko** [likeastore/ngDialog#266]
closeByDocument not work if i use master branch and get css from bower. If i click at overlay, i get back 
```<div id="ngdialog1">```
If i use css from https://rawgit.com/likeastore/ngDialog/0.4.0/css/ngDialog.min.css - all work

Didn`t know what the difference.

http://plnkr.co/edit/57nNpvYChYAVI9k0hT8C

**Comment by mcassagnes** [comment]
Same problem here

**Comment by Cornally** [comment]
The wrapping "<div class='ng-dialog'>" element is trapping the mouse click event that is intended for "<div class="ng-dialog-overlay">.  A workaround is to check the clicked target for the alternate class:

Modified ngDialog.js (~line 570):
closeByDocumentHandler = function (event) {
                                var isOverlay = options.closeByDocument ? ($el(event.target).hasClass('ngdialog-overlay') || ($el(event.target).hasClass('ngdialog'))) : false;
                                var isCloseBtn = $el(event.target).hasClass('ngdialog-close');

                                if (isOverlay || isCloseBtn) {
                                    publicMethods.close($dialog.attr('id'), isCloseBtn ? '$closeButton' : '$document');
                                }
                            };

**Comment by egor-smirnov** [comment]
was introduced by changes from other ticket; please check if it works as intended with master.
