### ISSUE TITLE
ngDialog.css illegal token / character

### ISSUE THREAD

**Issue by OnamChilwan** [likeastore/ngDialog#268]
Hello, I was wondering if perhaps maybe my setup is incorrect or if there is a bug in the code. Basically, I am trying to use ngDialog but for some odd reason when I add it and spin up my page I get an error stating there is an illegal character / token:

SyntaxError: illegal character
@-webkit-keyframes ngdialog-fadeout {

Any ideas what the cause maybe?

**Comment by egor-smirnov** [comment]
Aren't you adding `ngDialog.css` as script inside script tag instead of link tag?

**Comment by OnamChilwan** [comment]
Bugger sorry yes had it my bundle config as was being added as a script not a style sheet.
