### ISSUE TITLE
karma + requirejs and ngDialog

### ISSUE THREAD

**Issue by jbarros35** [likeastore/ngDialog#273]
I have a project with several controllers using ngDialog, but when trying to setup my karma config I cannot make it happen. The error rose is:

Uncaught Error: Mismatched anonymous define() module: function (angular) {
    'use strict';

    var m = angular.module('ngDialog', []);
...

karma.conf.js
'files: [
      'bower_components/jquery/dist/jquery.js',
     // 'bower_components/crypto-js/sha256.js',
      'bower_components/bootstrap/dist/css/bootstrap.min.css',
      'bower_components/angular-mass-autocomplete/massautocomplete.theme.css',
      'bower_components/ngDialog/css/ngDialog.css',
      'bower_components/ngDialog/css/ngDialog-theme-default.css',
      'bower_components/angular/angular.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/angular-loader/angular-loader.js',
      'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'bower_components/ngstorage/ngStorage.js',
      'bower_components/angular-mass-autocomplete/massautocomplete.js',
      'bower_components/bootstrap/dist/js/bootstrap.js',
      'bower_components/ngDialog/js/ngDialog.js',
      'bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
      'test/test-main.js',
      'login/login.js',
      'layout/menu.js',
      'home/home.js',
      'profile/signup.js',
      'layout/utils.js',
      'app.js',
      'test/*.js',
    ],'

I tried everything but cannot make it works.
'
bower.json
"dependencies": {
    "angular": "1.4.x",
    "angular-route": "1.4.x",
    "angular-loader": "1.4.x",
    "angular-mocks": "~1.4.x",
    "html5-boilerplate": "~4.3.0",
    "requirejs-text": "2.0.x",
    "requirejs": "2.1.x",
    "bootstrap": "~3.3.4",
    "angular-resource": "~1.4.0",
    "angular-bootstrap": "~0.13.0",
    "ngstorage": "~0.3.5",
    "crypto-js": "~3.1.5",
    "ngDialog": "~0.4.0",
    "ngInfiniteScroll": "1.0.0",
    "jquery": "~2.1.4",
    "angular-mass-autocomplete": "~0.2.3",
    "angular-sanitize": "~1.4.1",
    "angular-touch": "~1.4.1"
  },
  "resolutions": {
    "angular": "1.4.1"
  }'

**Comment by egor-smirnov** [comment]
Not 100% sure that this is related to ngDialog itself.

First, could you show content of the file that is using ngDialog?

**Comment by jbarros35** [comment]
login.controller('loginCtrl', ['$scope', '$location', 'Main', 'ngDialog', '$route', 'LS',
		function($scope, $location, Main, ngDialog, $route, LS) {
            // check environment variable
            Main.env(function(msg){
                    if (msg.env=='development'){
                        // set development user
                       var user = {email: "josecarlos@gmail.com",
                            token:"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9" +
                            ".eyJlbWFpbCI6Impvc2VjYXJsb3MuYmFycm9zQGdtYWlsLmNvbSIsImlhdCI6MTQzNTQzNjMyOSwiZXhwIjoxNDM1NTIyNzI5fQ" +
                            ".olCGwv3TYKfWYk5gDHr13miIP9e-jEj6eLvt4Jxz40k"};
                        ngDialog.closeAll();       
                        LS.setData('token', user.token);
                        $scope.changeLogged(true);
                        return;
                    }
                },
            function(err){
                console.log('error getting env variable');
            });
}

this code works well, but I cannot test it.

**Comment by jbarros35** [comment]
Another line here:

http://requirejs.org/docs/errors.html#mismatch
at http://localhost:9878/absoluteC:/Users/jose/node/heroku/desolate-taiga-1397/node_modules/requirejs/require.js?f9d7ac1ba78c53a51fd346e3901a5f406f060f44:141

**Comment by egor-smirnov** [comment]
Ok, thank you. Still I don't see anything that could cause this error inside your code.

Could you prepare some github repository that reproduces this issue?

**Comment by jbarros35** [comment]
sorry guys it was an error at config karma.conf
correct:
{pattern:'bower_components/ngDialog/js/ngDialog.js', included: false},
wrong:
bower_components/ngDialog/js/ngDialog.js'

thank you very much.
