### ISSUE TITLE
Dialog id should be available in dialog's scope.

### ISSUE THREAD

**Issue by MiguelMike** [likeastore/ngDialog#274]
With a bit of a hack it's possible to pass the dialog's id to the scope:

```
config{
    // dialog config
}

var dialog = ngDialog.open(config);
config.data.id = dialog.id;
```
The last line makes the `id` available in the ngDialogData.

It's not possible to do that using `openConfirm()` as it returns promise. Therefore, this dialog's scope has no way of knowing what the id of a dialog is.

**Comment by egor-smirnov** [comment]
Should be available as `$scope.ngDialogId`. For example refer to `examples/` folder.
