### ISSUE TITLE
custom logic on close

### ISSUE THREAD

**Issue by SET001** [likeastore/ngDialog#276]
In my case dialog template have 2 states and if it is in second state then `close` button should not close whole dialog but just switch template to first state. So I have to put some logic in `preCloseCallback` but I need access to scope in it, which currently I have not. Are there any other ways to do this?

**Comment by SET001** [comment]
Currently I changed `closeDialog` to be like this
```javascript
closeDialog: function ($dialog, value) {
    var preCloseCallback = $dialog.data('$ngDialogPreCloseCallback');
    var id = $dialog.attr('id');
    var scope = scopes[id];
    if (preCloseCallback && angular.isFunction(preCloseCallback)) {
        var preCloseCallbackResult = preCloseCallback.call($dialog, value, scope);
```

but I don't know if this is the best solution

**Comment by egor-smirnov** [comment]
@SET001 I am not sure that using of `preCloseCallback` is the best way to achieve what you need.

Could you handle switching of states inside dialog's controller? (for adding controller to your dialog use this option - https://github.com/likeastore/ngDialog#controller-string--array--object). 

As an example, you could have code like this:

```javascript
ngDialog.open({
    template: 'externalTemplate.html',
    controller: ['$scope', 'otherService', function($scope, otherService) {
        $scope.switchToStateOne = function() {
              // do actual switching
        }
    }]
});
```

Then inside template for this dialog you will have:

```html
<button type="button" ng-click="switchToStateOne()">Switch to state 1</button>
```

Will something like this work for your case?

**Comment by egor-smirnov** [comment]
@SET001 For more examples, you could refer to this file - https://github.com/likeastore/ngDialog/blob/master/example/index.html
