### ISSUE TITLE
trapFocus breaks on Mac if <a> is the last focusable element

### ISSUE THREAD

**Issue by roaks3** [likeastore/ngDialog#281]
If the dialog ends with an `<a href="...">`, ngDialog will assume that it is focusable, but on Mac by default anchors are not focusable.  As a result, the final tab key press will skip the anchor and break out into the browser/rest of page.

The best solution that I can come up with is to explicitly mark the anchor with tab-index="-1", so that it is never considered focusable for any browser, but the current implementation does not honor tab-index="-1".

**Comment by roaks3** [comment]
For more context:
- This does not occur on Chrome, I've only seen the incorrect behavior on Firefox and Safari.
- I've only tested on Mac
- Occurs on ngDialog 0.4.0 and master

Example: http://jsbin.com/hejifotaqo/edit?html,js,output

**Comment by egor-smirnov** [comment]
Thank you for providing example and description of the problem. Will revisit this later when have enough time.
