### ISSUE TITLE
In a hybrid app input hides behind the virtual keyboard

### ISSUE THREAD

**Issue by suriyagp** [likeastore/ngDialog#282]
I am using ngdialog on ahybrid app, That has several input boxes. If i tab on the bottom most text box. the keyboard get invoked and it overlaps the input field?

Actually it works fine fine on iOS have problem only on android how to solve that??

**Comment by egor-smirnov** [comment]
I don't see any relation of your question to `ngDialog`. Text inputs inside dialog have nothing to `ngDialog` itself. 

As a solution I would suggest following workaround. As soon as dialog is opened, focus some other block  (with `tabindex` specified) using JavaScript. This way input field won't be focused and virtual keyboard won't appear. Not nice workaround, but it could work.

Feel free to re-open an issue and provide additional information / code if I am wrong and it has relation to `ngDialog`.
