### ISSUE TITLE
Accessing parent controller [controllerAs] without injecting $scope

### ISSUE THREAD

**Issue by razvanbalosin** [likeastore/ngDialog#288]
Is there any way this can be achieved? as by specifying `scope: $scope` to the dialog, you'd still have to inject `$scope` into the parent/external controller

**Comment by egor-smirnov** [comment]
From what I know there is no such possibility in Angular 1.x. Review SO threads below please:

http://stackoverflow.com/questions/26309323/how-to-access-parent-property-using-controller-as-notation
http://stackoverflow.com/questions/21453697/angularjs-access-parent-scope-from-child-controller
http://stackoverflow.com/questions/26647460/accessing-inherited-scope-with-controller-as-approach

As this is not `ngDialog` specific question, I will close this issue for now. But feel free to add something. It would be nice to know the way of accessing parent controller without injecting `$scope`.

**Comment by tsears** [comment]
@razvanbalosin: set controller to a function that returns the current controller (e.g. controller: () => { return this; }

Plunker: https://plnkr.co/edit/2sjXCiWKicF0og41vkVw?p=preview
