### ISSUE TITLE
Maybe this directive should provide a 'width' options?

### ISSUE THREAD

**Issue by natee** [likeastore/ngDialog#29]
When i want to create different size dialog,i have to change the source code or do something other .

In your code ,you give the 'width' to 'ngdialog' in stylesheet 'ngDialog-theme-default.css'

I change the source code 

``` js
var dialogWidth;
dialogWidth = options.width + "px" || "438px";
$dialog.html('<div class="ngdialog-overlay"></div><div class="ngdialog-content" style="width:'+dialogWidth+'">' + template + '</div>');
```

then i can use 'width' options to resolve this problem

**Comment by dgoncalves1** [comment]
Sorry for waking up this old thread @voronianski , but I'm using your ngDialog with gulp and I need to change the width, whenever i change the theme in the controller. 

```
ngDialog.open({
    template: tpl.path,
    className: 'ngdialog-theme-mycustom'
 });
```

and I add the styles to my main css, doesn't work

Now if i just modify the classes by default,  they still keep getting overlapped by the ones in vendor folder of the project (the default ones) in min.css

No idea how to achieve this.
