### ISSUE TITLE
Can the browser back button return to an open modal? 

### ISSUE THREAD

**Issue by HarrisRobin** [likeastore/ngDialog#290]
Hi,

So I understand that to open the modal, one needs to call ngDialog.open(), however I have a requirement that means I need to be able to click 'back' and navigate back to the previous page with the modal already open and I don't necessarily want to call ngDialog.open. This is a similar behaviour to Trello or Facebook. Has anyone figured out how to do this using ngDialog by pushing the state to the url?

Cheers

**Comment by egor-smirnov** [comment]
@HarrisRobin Is this link helpful for you? https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state. Try to adapt it to ngDialog API.

**Comment by HarrisRobin** [comment]
@egor-smirnov thanks for the link. Will read it, although I have come up with a solution that worked for me.

What I did was the following: 
Using ui-router, I simply created a child route that's purpose is to open that modal and whenever someone lands on that route I call ngDialog.open().

I hope this helps others who have ran into this issue.

**Comment by egor-smirnov** [comment]
@HarrisRobin actually what you did is similar to what is described at https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state
