### ISSUE TITLE
publish next version to bower / npm

### ISSUE THREAD

**Issue by jbimberg** [likeastore/ngDialog#293]
According to the (closed) issue "Allow using higher version of angular" #244, as everything seems prepared and the downloaded version works well, could you please publish the current master?

**Comment by egor-smirnov** [comment]
ping @voronianski

**Comment by voronianski** [comment]
@jbimberg @egor-smirnov ok, I'll do it today

**Comment by egor-smirnov** [comment]
thanks!

**Comment by voronianski** [comment]
@egor-smirnov I've published `0.5.0` to npm, could you also update [changelog](https://github.com/likeastore/ngDialog/blob/master/CHANGELOG.md) with all features/changes in this version?
