### ISSUE TITLE
ngDialogProvider.setForceHtmlReload(true) is not a function?

### ISSUE THREAD

**Issue by vrghost242** [likeastore/ngDialog#295]
Having some issues with one of the dialogs (it has a LOT of buttons, three pages worth) and only renders the first page or so, if you scroll down and click the scree where there should be a button, the next bunch loads. 
Thought it may have something with loading, and found the option setForceHtmlReload. Seems grand, so I thought I would use it. However, when I set the below: 

ResourceEdge.config(function (ngDialogProvider) {
    ngDialogProvider.setForceHtmlReload(true);
});

I get: 
TypeError: ngDialogProvider.setForceHtmlReload is not a function

The angular app have another config block for some other services, but adding it there gives the same issue.

**Comment by egor-smirnov** [comment]
Have you tried `setForceBodyReload`?

**Comment by vrghost242** [comment]
That seems to work (no complaints when loading page). 

Does not resolve my problem, but thinking my issue may be related to Chrome rendering engine rather than ngDialog. For some reason chrome just does not show all the buttons, if I change screens between word and chrome, new buttons appear, and issue does not occur on Safari. (Page renders perfectly on both if loaded directly rather than via ngDialog)

Might be that setForceHtmlReload as an option is broken in version 0.4.0

**Comment by egor-smirnov** [comment]
`setForceHtmlReload` was added recently and is not available under 0.4.0 (open https://cdnjs.cloudflare.com/ajax/libs/ng-dialog/0.4.0/js/ngDialog.js and search by `setForceHtmlReload`, this will throw no results).

I am closing issue for now as it seems to me that it's very dependable on your setup / application. Feel free to re-open if you'll have some live code example showing the issue.
