### ISSUE TITLE
How to get the latest commits via bower?

### ISSUE THREAD

**Issue by johnc1984** [likeastore/ngDialog#298]
Hi, 

I really want the latest version of the ngDialog in an app i run, specifically I would like the use of the commit from: https://github.com/likeastore/ngDialog/commit/9ee76c19b225326ea11362680284c4f6c663293e

I am using bower to manage the client side 3rd party scripts, but i cannot seem to get bower to install all the latest code that is visible in github. Is there a process I can follow to achieve this or is there a release that i need to wait for?

Thanks,
John

**Comment by DavidEBest** [comment]
You should be able to specify the specific commit with the format:
```
bower install --save git://github.com/likeastore/ngDialog#9ee76c19b225326ea11362680284c4f6c663293e
```

(from http://stackoverflow.com/questions/18639488/bower-git-package-with-a-commit-id)

**Comment by johnc1984** [comment]
ah, right.. however this app has been configured using a bower.json. Is the only option to wait in that case?

This is the bower dependicies list:
  "dependencies": {
    "jquery": "latest",
    "jquery-ui": "latest",
    "angular": "latest",
    "angular-mocks": "latest",
    "angular-route": "latest",
    "angular-resource": "latest",
    "angular-animate": "latest",
    "angular-sanitize": "latest",
    "angular-scroll-animate": "latest",
    "angular-slick-carousel": "latest",
    "ionicons": "latest",
    **"ngDialog": "latest"**
  },

**Comment by DavidEBest** [comment]
Should be able to just change the `latest` bit to the git commit.
```
"dependencies": {
"jquery": "latest",
"jquery-ui": "latest",
"angular": "latest",
"angular-mocks": "latest",
"angular-route": "latest",
"angular-resource": "latest",
"angular-animate": "latest",
"angular-sanitize": "latest",
"angular-scroll-animate": "latest",
"angular-slick-carousel": "latest",
"ionicons": "latest",
"ngDialog": "git://github.com/likeastore/ngDialog#9ee76c19b225326ea11362680284c4f6c663293e"
},
```

**Comment by johnc1984** [comment]
That worked nicely. Thank you very much.

**Comment by voronianski** [comment]
@johnc1984 @DavidEBest git version tag is updated with latest as well, so bower should resolve it soon.
