### ISSUE TITLE
trapFocus causes issues

### ISSUE THREAD

**Issue by Ozonni** [likeastore/ngDialog#300]
I have very simple case. I have a dialog with a form. Inputs, selects, date pickers. Before everything was ok, but once i updated to 0.4 i started getting these problems.
When you open dialog, it sets automatically focus to the focusable element and it's configured by trapFocus which is 'true' by default. It's annoying, because date pickers open automatically even if it's not a first element. I would say it make sense to set trapFocus to 'false' by default to not to brake backward capability.

**Comment by egor-smirnov** [comment]
@Ozonni from what I see inside `REAME.md` file:

> trapFocus {Boolean}
>When true, ensures that the focused element remains within the dialog to conform to accessibility recommendations. Default value is true

I am not an expert in field of accessibility, so honestly don't know whether it's valid or not. 

Maybe any other have some input on this?

**Comment by egor-smirnov** [comment]
Might be related to https://github.com/likeastore/ngDialog/issues/154 (But i didn't give a closer look).

**Comment by faceleg** [comment]
You can set global defaults using https://github.com/likeastore/ngDialog#setdefaultsoptions

```JS
var app = angular.module('myApp', ['ngDialog']);
app.config(['ngDialogProvider', function (ngDialogProvider) {
    ngDialogProvider.setDefaults({
        trapFocus: false
    });
}]);
```

Also see #310.
