### ISSUE TITLE
How to prevent double dialog opening 

### ISSUE THREAD

**Issue by johnc1984** [likeastore/ngDialog#309]
We have found that on occasion an ngdialog is open twice when the user double clicks, this happens more frequently in Firefox.

Is there a global trick to preventing this happen?

**Comment by faceleg** [comment]
How are you opening your dialog?

One fix is to wrap the ngDialog.open in a function that stores the returned object and uses that to determine whether the dialog is open or not.

**Comment by faceleg** [comment]
I am open to a PR adding a debounce option that takes a unit of time in ms and prevents open from calling through if more than one call to open is made within said time.

**Comment by faceleg** [comment]
Feel free to re-open or send a PR
