### ISSUE TITLE
ngDialog does not close on clicking back button 

### ISSUE THREAD

**Issue by sajangurung2015** [likeastore/ngDialog#314]
everything is working fine with ngDialog except the ngDialog button does not close itself on clicking the back button.

**Comment by leocaseiro** [comment]
Try define **closeByNavigation** as **true**

Eq.


    ngDialog(open{
        closeByNavigation: true
    });

**Comment by chetanbuddh** [comment]
closeByNavigation as true is not working for me

**Comment by hulkish** [comment]
closeByNavigation also not working for me
