### ISSUE TITLE
Custom size doesn't seem to work 

### ISSUE THREAD

**Issue by dgoncalves1** [likeastore/ngDialog#316]
I'm using your ngDialog with gulp and I need to change the width, whenever i change the theme in the controller. 

```
ngDialog.open({
    template: tpl.path,
    className: 'ngdialog-theme-mycustom'
 });
```

and I add the styles to my main css, doesn't work

Now if i just modify the classes by default,  they still keep getting overlapped by the ones in vendor folder of the project (the default ones) in min.css

No idea how to achieve this.

**Comment by faceleg** [comment]
Please provide a basic working example in jsfiddle or plunkr

**Comment by dgoncalves1** [comment]
@faceleg Sorry for the late response, since i could not find a way to fix this i dropped usage of ngDialog and moved to Bootstrap regular modal which do the trick. I'll provide a plunkr as soon as I can but you can close this issue if you feel so anyway.

Thanks

**Comment by faceleg** [comment]
Thanks for replying - it's definitely relevant!

I ask for the working example so I can poke it, figure out what is wrong and write a unit test to cover any fix I make.
