### ISSUE TITLE
AngularAMD injector

### ISSUE THREAD

**Issue by ivolvicente** [likeastore/ngDialog#320]
Hi, 

I'm have problems when try to load ngDialog with angularAMD, any ideias why?

Just return error on $injector:modulerr

**Comment by faceleg** [comment]
It'd be a great help if you could put together a basic example of this error on plunkr or jsfiddle

**Comment by ashokmohantyperkinelmer** [comment]
I am facing same issue loading ngDialog with angularAMD and requirejs.

Please find the plunker link.

http://plnkr.co/edit/7HlSunVsCKOkr11RP8eX?p=preview

**Comment by faceleg** [comment]
Check http://plnkr.co/edit/jMSk8lSVp4kSbkjIAuQB?p=preview
