### ISSUE TITLE
How to close a dialog manually?

### ISSUE THREAD

**Issue by archasek** [likeastore/ngDialog#321]
While my default close button doesnt work (issue #319), I want to do something like this:

```
          $rootScope.$on('ngDialog.opened', function (event, $dialog) {
            $dialog.dialog.find('.ngdialog-close').on('click', function() {
              $dialog.close();
            });
          });
```

But of course it doesn't work, because $dialog (or $dialog.dialog) doesn't have the `close()` method. How can I do this?

At the moment I just do `$dialog.dialog.remove()` (jQuery's remove method), but it leaves `ngdialog-open` class in `body` and probably other things I do not want to have.

Thanks.

**Comment by faceleg** [comment]
`ngDialog.close(id)`

**Comment by archasek** [comment]
It doesn't work. My code:

```
          $rootScope.$on('ngDialog.opened', function (event, $dialog) {

            $dialog.dialog.find('.ngdialog-close').add($dialog.dialog.find('.icon--close')).on('click', function() {
              ngDialog.close($dialog.dialog.attr('id'));
            });
          });
```

**Comment by faceleg** [comment]
Your code is much more complicated than `ngDialog.close("id")`.  Try to expand your code out, log each step, and try to isolate which part isn't working.

I've written unit tests to assure myself that `ngDialog.close` is working how I expect - this doesn't mean there are no bugs around it, it just makes me think that something else is going on here.

**Comment by archasek** [comment]
this line doesn't work:
`ngDialog.close($dialog.dialog.attr('id'));`

`$dialog.dialog.attr('id')` works OK and returns the ID of dialog.

**Comment by faceleg** [comment]
Are you using the latest ngDialog?

**Comment by archasek** [comment]
Of course I downloaded upaded ngDialog script (btw. you forgot to minify it and upload to github).

**Comment by faceleg** [comment]
Yeah I did forget to do that.

Well I'm stumped. Would you be able to write a test that shows it not working? You can add to this test: https://github.com/likeastore/ngDialog/blob/master/tests/unit/ngDialog_insideDirective.js

**Comment by archasek** [comment]
Unfortunately, I won't be able to do this in the nearest time.
Sadly, I will use my workaround instead :(

**Comment by faceleg** [comment]
Have you confirmed that your `.on` callback gets called?

**Comment by archasek** [comment]
`$on('ngDialog.opened')` is called.
`$on('ngDialog.closing')` is called.
`$on('ngDialog.closed')` is not called.

**Comment by faceleg** [comment]
No I meant your onclick handler
