### ISSUE TITLE
template use bootstrap set grid is not work

### ISSUE THREAD

**Issue by fuqiang89** [likeastore/ngDialog#325]
template use bootstrap  set grid is not work:

```
<script  type="text/ng-template" id="stableEditTmpl">
    <div class="col-lg-12">
        <div class="col-lg-10">
            <div class="row"> <span>row01</span></div>
        </div>
        <div class="col-lg-2">
            <div class="row"> <span>row02</span></div>
        </div>
    </div>
       </script>
```

**Comment by faceleg** [comment]
Sorry you're having an issue!

We need more than just this to help you out though, please provide a working example in Plunkr or JSFiddle.

**Comment by fuqiang89** [comment]
@faceleg
sorry,That is my fault.  I use  Plunkr  runing a example that is work. http://plnkr.co/edit/1SjsMxbPjYarwADgSgDs?p=preview
final, i find one css file 

```
.ngdialog-content{
    padding-bottom: 0 !important;
    padding-right: 20px !important;
}

```
:cold_sweat::cold_sweat::cold_sweat::cold_sweat:

Thanks for your quick response.:smile:

**Comment by faceleg** [comment]
No problem! Happy it's sorted :)
