### ISSUE TITLE
Can't close dialog in Safari

### ISSUE THREAD

**Issue by MiguelMike** [likeastore/ngDialog#327]
Clicking the close button does not close the dialog.

It breaks on `preCloseCallback` without any error enven if the callback promise returns `true`

**Comment by faceleg** [comment]
Can you please put together a minimal test case that shows this error?

**Comment by faceleg** [comment]
I've added some basic protractor tests that show `close` working in it's basic form in Safari.

**Comment by MiguelMike** [comment]
It seems to be working fine in a very basic environment. I'm trying to pinpoint why it doesn't work in my project and only in Safari.

**Comment by faceleg** [comment]
I'll leave this issue open for now, if you do discover a reason I'd be interested to know what it is

**Comment by MiguelMike** [comment]
Forcing the value of `animationEndSupport` to `false` (`var animationEndSupport = false;`) solves the problem.

**Comment by MiguelMike** [comment]
I couldn't find the cause of this problem. The dialog just remains open with `ngdialog-closing` class.

However, I found a `disableAnimation` option, which disables the closing animation. Even though it's only a partial solution to the problem I can live with it.

I'm closing this issue.

**Comment by faceleg** [comment]
If you made a jsfiddle or plunker while testing is be keen to see it! Things like this really bug me. 

If not, thanks for updating us.

**Comment by fedeoo** [comment]
I'ever encountered this problem. Finally, I found the reason is that I set the ngdialog-closing style to disable the effect of closing dialog.

     -webkit-animation: ngdialog-fadeout 0s;

Safari won't trigger the animationEnd event. @MiguelMike
