### ISSUE TITLE
Option to put the overlay outside of dialog

### ISSUE THREAD

**Issue by abelan** [likeastore/ngDialog#328]
In case of 'appendTo' I would like to add the overlay directly to the body (css is the reason in my case, e.g. 'z-index').

**Comment by faceleg** [comment]
> appendTo {String}

> Specify your element where to append dialog instance, accepts selector string (e.g. #yourId, .yourClass). If not specified appends dialog to body as default behavior.

**Comment by abelan** [comment]
mmm, I may read the manual...
and I use 'appendTo' without issues except one: how to move the overlay div outside of dialog (e.g. to the body)?
So  &lt;div class="overlay">&lt;/div> should be added directly to the body.

I suppose it is enhancement not a bug.

**Comment by faceleg** [comment]
Sorry I don't understand the question?

**Comment by abelan** [comment]
I have a layer in that I've put a dialog (I have to show the dialog after specific element). But the layer have to be above the overlay (always visible). In current implementation I can't use z-index. So I see just one solution - insert the overlay directly in the body.

**Comment by faceleg** [comment]
If you can modify ngDialog to do this, I'm interested to see it.

**Comment by abelan** [comment]
I can't :) that's why I'm asking developers to make it. I see it is a rare case but I need it...

**Comment by faceleg** [comment]
We're I in your situation, I would look at changing my code to work with the library, not the other way round
