### ISSUE TITLE
Can I pass any parameter to the template?

### ISSUE THREAD

**Issue by neesonqk** [likeastore/ngDialog#337]
There is a user table in my case which contains many users records, 

| User ID        | Name   |
| ------------- |:-------------:|
| 001  | Jason |
| 002  | James |
| 003  | Jean   |

while clicking each user row this ngDialog will appear to show this user's details information, so each click event is binding to the same function `showDetails()`, from here I can pass some variables to this function like `showDetails(user)`, the function should looks like,

```
$scope.showDetails = function(user){
    ngDialog.open({
            template: 'user_detail_popup.html',
            disableAnimation: true,
            appendTo: '.main-context'
        });
}
```

then how to populate the `user` info to that  `user_detail_popup.html`?

**Comment by faceleg** [comment]
Sure, have a look at the `scope` option: https://github.com/likeastore/ngDialog#scope-object

**Comment by faceleg** [comment]
Sure, have a look at the `scope` option: https://github.com/likeastore/ngDialog#scope-object
