### ISSUE TITLE
Upgrading from 0.5.1 to 0.5.4 breaks webpack

### ISSUE THREAD

**Issue by mike-ward** [likeastore/ngDialog#340]
When I run `webpack -p` I get the following error.

ERROR in ./~/ng-dialog/js/ngDialog.js

Module not found: Error: Cannot resolve module 'ngDialog' in C:\Users\Mike\Documents\GitHub\amgen-tbmis\amgen-tbmis\js\node_modules\ng-dialog\js

 @ ./~/ng-dialog/js/ngDialog.js 17:8-19:10

**Comment by jecede** [comment]
The names in package.json and ngDialog.js line 17 don't match. Here the module is defined as ngDialog, and in package.json as ng-dialog. So loaders like webpack get confused.
Editing ngDialog into ng-dialog on line 17 fixes this issue.

**Comment by faceleg** [comment]
@jecede PR?

**Comment by voronianski** [comment]
@mike-ward @faceleg @jecede pushed version `0.5.5` with this fix to npm, as well as **renamed package in bower to `ng-dialog`** in order to match with npm.

**Comment by mike-ward** [comment]
Gotta love open source. Thanks guys...

**Comment by faceleg** [comment]
@voronianski thanks, apologies if I had caused this breakage with my recent changese
