### ISSUE TITLE
Return module name (string) instead of module

### ISSUE THREAD

**Issue by alexbeletsky** [likeastore/ngDialog#342]
As the ES6 and `import` module management getting traction, there is new convention that angular.js components should follow. In order to be able to write code like,

```js
import cookies from 'angular-cookies';
import router from 'angular-ui-router';
import angulartics from 'angulartics';
import angularticsSegment from 'angulartics-segment';
import ngDialog from 'ng-dialog';

let app = angular.module('app', [
            angulartics,
            angularticsSegment,
            cookies,
            router,
            ngDialog
        ]);
```

Currently you have to import ngDialog, but use `ngDialog` as string in dependencies, which make ngDialog as unused variable and provokes lint errors.

check [angulartics](https://github.com/angulartics/angulartics-segment/blob/master/lib/index.js) as example.

**Comment by egor-smirnov** [comment]
Will take this one.

**Comment by egor-smirnov** [comment]
@alexbeletsky should be available at master branch now (`npm install --save git+https://git@github.com/likeastore/ngDialog.git`)
