### ISSUE TITLE
pass "self" as the scope - is it possible ?

### ISSUE THREAD

**Issue by siv123456** [likeastore/ngDialog#344]
Hi,

i'm learning angularJS and would like to use ngDialog - looks like a great add-on.
from what i read, it is possible to pass the $scope of a controller to the ngDialog.open options.
thing is , i am not passing $scope to my controller but using "var self = this;" in my controller code ,its something i read in this article (http://toddmotto.com/digging-into-angulars-controller-as-syntax/).

so now ,can i still use scope option and pass "self" as the scope ( i couldn't get it to work so i assume its not the right thing to do). can i do anything else to pass all controller variables etc to the dialog i open ?

let me know if you need to see my code if my question is not clear enough and thanks for the great work in advance.

Sivan

**Comment by faceleg** [comment]
It would be helpful to see your best attempt to create a working example in JSFiddle or Plunkr

**Comment by egor-smirnov** [comment]
What about something like this?

```javascript
ngDialog.open({
    template: 'externalTemplate.html',
    className: 'ngdialog-theme-plain',
    scope: self
});
```

**Comment by siv123456** [comment]
Hi,

its a good thing i'm new to "real" programming (i come from scripting languages background , short code not too complex), it makes me try everything until i succeed, so even though i'm using the "var self = this;" in my controller ,i decided to inject the $scope into the controller and pass it on to dialog.open. it seems to work so we're good here. now i have another issue but i'll close this ticket and if needed open another one. 

thanks for your time. 
Sivan
