### ISSUE TITLE
Protractor tests broken

### ISSUE THREAD

**Issue by faceleg** [likeastore/ngDialog#346]
Appears that protractor can't connect to sauce labs for some reason, investigating

**Comment by egor-smirnov** [comment]
@faceleg yeah I was going to report that issue. Thank you for noticing.

**Comment by faceleg** [comment]
OK checkout https://github.com/likeastore/ngDialog/pull/322

I've overhauled the protractor code **again**, to use firefox.

Ideally it will still use sauce labs (and therefore run IE, Safari, Chrome and Firefox) on our master & develop, but this is obviously untested, and won't be until the PR is merged.

I'll leave this issue open to track any issues we have after the aforementioned PR is merged.

**Comment by faceleg** [comment]
I merged it and will monitor the build

**Comment by faceleg** [comment]
Can't get sauce working, out of time. 

Set all builds to use firefox only for now.
