### ISSUE TITLE
Can you update the className dynamically?

### ISSUE THREAD

**Issue by maggo** [likeastore/ngDialog#348]
Hi, I'm trying to update the className of the dialog when something happens inside the dialog's controller (form submit) so that it displays a confirmation message and shrinks to a reasonable size.

Is there a way to update the class dynamically or somehow get the current dialog element? Right now I'm querying the open dialog directly with angular.element which just isn't nice. Thanks!

**Comment by faceleg** [comment]
You could listen for the `ngDialog.opened` event, which would get you the `$dialog` element:

https://github.com/likeastore/ngDialog#events

**Comment by maggo** [comment]
Okay that's a way thanks!

**Comment by faceleg** [comment]
I think the reason you can't have `$dialog` returned from `ngDialog.open` is that there are promises resolved. 

A breaking change would need to be made to have `ngDialog.open` return a promise. There is an issue discussing this but I forget what ID it is.
