### ISSUE TITLE
can't click with mouse on element in my dialog - tab working fine

### ISSUE THREAD

**Issue by siv123456** [likeastore/ngDialog#349]
Hi,

i'm trying to learn how to use the ngDialog and built a small page with a button that when i click it ,a dialog with text input and button is opened.
![image](https://cloud.githubusercontent.com/assets/10827288/10319877/1ffd1ef2-6c79-11e5-9bd4-72657d8adb01.png)

i attached an image showing the button and the dialog opened after i clicked it.
before i go and try loading my code to jsfiddle etc ,is there any known reason for this to happen ?

thanks in advance
Sivan

**Comment by faceleg** [comment]
Have you included the ngDialog css?

**Comment by siv123456** [comment]
Hi,

yes ,i'm using the ngDialog css file ( got this line in my html ) :
<link rel="stylesheet" type="text/css" href="ngDialog-master/css/ngDialog.css">

just to be on the safe side ,i checked that changing this css really makes a difference and its ok.
i think i managed to load my case on plunker ( first time i use it so i'm not sure you'll see my code) : http://plnkr.co/edit/tpl:8rFfZljYNl3z1A4LKSL2?p=streamer&s=f5zw5QewgOH6dccc

hope this helps.
thanks

**Comment by faceleg** [comment]
I still don't know what the issue was (don't understand what you mean) but I added a theme (there are two css files - the main one and a theme - I used the default theme).

http://plnkr.co/edit/ZS38BFyehdMZU1z9Aqqo?p=preview&s=f5zw5QewgOH6dccc
