### ISSUE TITLE
Including a directive inside the dialog causes a delay in rendering

### ISSUE THREAD

**Issue by rob-balfre** [likeastore/ngDialog#350]
Custom directives appear after the modal has finished rendering. Issue occurs even if the directive's template has been cached using $templateCache.

**Comment by faceleg** [comment]
Can you please make a jsfiddle or plunker example for us?

**Comment by rob-balfre** [comment]
Here you go:
http://embed.plnkr.co/dAOlOAJebO1fCXgwGMgp/preview

You should notice the ng-include directive appears during the animation.

I was going to post just the above! Then I tried it it with $templateCache and got this...
http://embed.plnkr.co/D3cJJivZkMytLo4NcQwS/preview

Issue must be something else in my code, I'll investigate! Thanks for the quick reply :)

**Comment by rob-balfre** [comment]
It was a dynamic templateUrl I was using in my directive.

**Comment by faceleg** [comment]
Yay! Glad it got sorted :)
