### ISSUE TITLE
ngDialog does not return to original scrollY position when closed or return to parent view

### ISSUE THREAD

**Issue by morph85** [likeastore/ngDialog#357]
Currently ngDialog doesn't return to original scrollY position and being reset to top of the parent view instead. I checked jQuery by listening to window.onScroll event but it wasn't triggered.

My workaround is:

    ...
    var scrollY = $window.scrollY;
    dialog.closePromise.then(function (data) {
        // workaround to return to original position
        $timeout(function() {
            $scope.$apply(function() {
                $window.scrollTo(0, scrollY);
            });
        }, 1000);
    });

**Comment by egor-smirnov** [comment]
This might be fixed very soon by PR  https://github.com/likeastore/ngDialog/pull/360.

**Comment by egor-smirnov** [comment]
@morph85 could you please check now with latest master version?

**Comment by morph85** [comment]
Noted but checking stopped due to concern raised in #360.

**Comment by JulianLaval** [comment]
Any progress on this? :)

**Comment by JulianLaval** [comment]
Oops, disregard previous message - the fault was entirely my own, having set `.ngdialog-open` to `height: 100%`.

Removing this seems to solve any issues with page scroll on both open and close - maybe this issue can be closed?
