### ISSUE TITLE
Make ngDialog not disappear when click outside of modal

### ISSUE THREAD

**Issue by darkmanAmazigh** [likeastore/ngDialog#362]
Hello,

How can i do to make my ngDialog not disappear when user click outside of the modal of ngDialog ?

Thanks All

**Comment by egor-smirnov** [comment]
@darkmanAmazigh try this option - https://github.com/likeastore/ngDialog#closebydocument-boolean. Use `false` as a value.

**Comment by darkmanAmazigh** [comment]
youpi it work
thank you @egor-smirnov

**Comment by davidCanche1994** [comment]
thank you @egor-smirnov working perfect!
