### ISSUE TITLE
Text selection on the modal is disabled by default

### ISSUE THREAD

**Issue by jpatel3** [likeastore/ngDialog#363]
Why the text selection on the modal is disabled by default, and instead of explicitly adding style, can we move it to the css.

I see following style gets added explicitly to the modal div.

touch-action: pan-y; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);

**Comment by faceleg** [comment]
I'm open to a PR that adds this functionality via an option, as it's default behaviour.

(with tests)

**Comment by jpatel3** [comment]
Sure. Any suggestion on option name and scope? 

Looking at the code, it seems to be added by -
var hammerTime = scope.hammerTime = $window.Hammer($dialog[0]);

I think should be option for allowTextSelection: true/false

**Comment by jpatel3** [comment]
Based on the option allowTextSelection value we can set the hammer behavior using following -

```
$window.Hammer($dialog[0], {
  cssProps: {
    userSelect: true
  }
});
```

**Comment by faceleg** [comment]
Looks good to me - will need  test or two to verify it doesn't break anything and that it works as expected.

@voronianski @egor-smirnov what do you think?

**Comment by jpatel3** [comment]
Sure. I can make the change and provide the pull request.

**Comment by faceleg** [comment]
You rock :tada: :tanabata_tree:
