### ISSUE TITLE
If I want to embed popup into some element using appendTo then why I cannot scroll a page?

### ISSUE THREAD

**Issue by AndrewEastwood** [likeastore/ngDialog#364]
It's more obvious when you're truing to append popup to some another element then it should appear in new place and stay there. If so then it's kinda embedded popup.
Can it be fixed or If somehow it's not a bug for creators can we add some option that tells ngdialog to be embedded and avoid adding ```ngdialog-open``` class name?

**Comment by faceleg** [comment]
Does this issue occur if using the master branch

**Comment by AndrewEastwood** [comment]
I'm using 0.4.0

**Comment by faceleg** [comment]
That's a very old version, can you please try with the latest version?

**Comment by faceleg** [comment]
I'm closing this - feel free to re-open if you have tried with the latest version and still run into the issue
