### ISSUE TITLE
Open Dialogbox before dom is created

### ISSUE THREAD

**Issue by georgi-kovachev** [likeastore/ngDialog#366]
My dialogbox needs time to be dom-ready because it has to load many element.s
But I want to show the dialog box first.
How can I show dialog box and data processing happens in background?

**Comment by faceleg** [comment]
you could open the dialog and do your processing in the dialog's controller?

**Comment by georgi-kovachev** [comment]
I am doing like this
ngDialog.open({
      template: 'templates/partials/subpanels/highlight.html',
      controller: 'HighlightController',
      className: 'subpanel-dialog'
})

**Comment by faceleg** [comment]
are you DOM elements in highlight.html?

**Comment by georgi-kovachev** [comment]
I have ng-repeat in side html file and it is large array

**Comment by faceleg** [comment]
Generally if your array is so large as to cause delays in dom rendering, you need to look into ways to reduce the rendering time OR split the array (i.e. with pagination).

Anything that causes periods of UI unresponsiveness is terrible for user experience.

**Comment by faceleg** [comment]
You could drop http://swimlane.github.io/angular-data-table/ and see if that helps.

**Comment by georgi-kovachev** [comment]
thanks
