### ISSUE TITLE
Adding a function to dialog's scope

### ISSUE THREAD

**Issue by MiguelMike** [likeastore/ngDialog#369]
Is it possible to add a function into the dialog's scope in such way that it can be accessed by `$scope.functionName()`?

I tried to achieve this using decorator, but it doesn't seem to work.

**Comment by faceleg** [comment]
Does this answer the question? https://github.com/likeastore/ngDialog#controller-string--array--object

**Comment by MiguelMike** [comment]
No, not really. Could you elaborate a bit on this?

**Comment by MiguelMike** [comment]
It's been some time since I posted this question, it's outdated.
