### ISSUE TITLE
ngdialog having problem on touch devices

### ISSUE THREAD

**Issue by suriyagp** [likeastore/ngDialog#371]
That is on android tabs and ipad devices, It get way from the screen on the presence of virtual keyboard.If tha dialog having a test box and get get boxed means virtual keyboard gets invoked at that time the dialog box just move away from the screen towards top. how to control the ngdialog at the presence of virtual keyboard? is there any work around for this? is there any fix for this issue?

**Comment by faceleg** [comment]
Are there any events you can subscribe to in order to be notified that the on-screen keyboard is going to be displayed?

**Comment by suriyagp** [comment]
no events are subscribed, that is default event of touch devices right? once you tap on the test box the virtual keyboard get invoked.

**Comment by faceleg** [comment]
Then you could listen for focus events on your text inputs and resize / move the dialog then.

I don't think this is an issue with ngDialog
