### ISSUE TITLE
Calculate the dialog placement dynamically according to its content?

### ISSUE THREAD

**Issue by sikko** [likeastore/ngDialog#372]
Hi,
I have an issue with large modal windows. At the moment, my dialog is centered (using absolute positioning and translateY -50%).
The problem here is that when the dialog content is higher than the screen, the top and the bottom of the dialog become hidden.
Ideally, I'd need to proceed this way:
- Set the visibility/opacity of the modal to 0
- Let the content load and lay out inside the dialog so that I can measure it
- If smaller than screen size, center it vertically
- If larger than screen size, position it to the top of screen, but allow page scroll to view the bottom of the dialog
- When properly positionned, set opacity back to 1

I know that's a lot of things but you get the idea.
Has Anyone managed to implement such a behaviour? or something similar? Or was I thinking this wrong in the first place?

Thanks

**Comment by marcelotm** [comment]
Is there ny solution yet?

**Comment by faceleg** [comment]
This is out of scope for this module. Functionality like this can be implemented in user-land code.
