### ISSUE TITLE
[Doc] Need clarification on CSS usage

### ISSUE THREAD

**Issue by PhiLhoSoft** [likeastore/ngDialog#373]
I see at the top of the ReadMe file:

> **Usage**
> You need only to include ngDialog.js and ngDialog.css (as minimal setup)

I suggest to include a line showing the CSS inclusion. Not because readers are dumb, but to stress out more the need for the CSS / to make it more obvious, as it is easy to overlook the mention...

    <link rel="stylesheet" href="assets/libs/ng-dialog/css/ngDialog.css">

or something similar.

Beside, it is not correct. Out of the box, with minimal code you give there, it just doesn't work: I get an overlay (after including the above CSS, otherwise I get nothing), but the dialog content was on the top-left of the page, with transparent background.
We need to include the default theme as well:

    <link rel="stylesheet" href="assets/libs/ng-dialog/css/ngDialog-theme-default.css">

I think it is worth mentioning at this point, even if you write about it later, because users like me are impatient to see it running in the app and try before reading the whole doc. :smile:

**Comment by faceleg** [comment]
If you make the suggested change to the docs and submit a PR, I'll happily review / merge it.

**Comment by egor-smirnov** [comment]
@PhiLhoSoft Thank you for a contribution!
