### ISSUE TITLE
Execute a function within Dialog when closing

### ISSUE THREAD

**Issue by markzolotoy** [likeastore/ngDialog#378]
How can I execute a function that is within a scope of Dialog when Dialog is closing? I can easily accomplish that for a cancel button that a user clicks on by calling $scope.closeThisDialog();. I would like to the same when a dialog is closing by other means.

Thanks

**Comment by jpatel3** [comment]
Did you try to pass [preCloseCallback] (https://github.com/likeastore/ngDialog#preclosecallback-string--function) in initialization?

```
ngDialog.open({ 
template: 'template.html', 
preCloseCallback:function(){ /* close actions */} 
});
```

**Comment by markzolotoy** [comment]
But the function that I need to execute on Close is within dialog's
controller not is the calling one as you are showing.

**Comment by Rorkal** [comment]
Maybe late but you can listen to 'ngDialog.closing' event like this :

```javascript
$scope.$on('ngDialog.closing', function () {
    $state.go('^');
});
```

**Comment by markzolotoy** [comment]
Thanks, will try.
