### ISSUE TITLE
NuGet Updates, stopped from 0.3.1

### ISSUE THREAD

**Issue by Cadey** [likeastore/ngDialog#381]
Hi guys, sorry if I missed some news regarding this however I was wondering who keeps the NuGet versions up to date as its currently trailing behind on version 0.3.1?

**Comment by faceleg** [comment]
@egor-smirnov @voronianski either of you know about NuGet?

**Comment by voronianski** [comment]
@faceleg nope, never published ngDialog there..

**Comment by egor-smirnov** [comment]
@faceleg same

**Comment by voronianski** [comment]
btw what is nuget?)

**Comment by egor-smirnov** [comment]
> NuGet is the package manager for the Microsoft development platform including .NET. The NuGet client tools provide the ability to produce and consume packages. The NuGet Gallery is the central package repository used by all package authors and consumers.

**Comment by egor-smirnov** [comment]
https://www.nuget.org/packages/ngDialog/ - according to that link, the person who published ngDialog there has username `mikeon`.

@Cadey any idea on how to contact that person?

**Comment by Cadey** [comment]
Hummm I have no idea, I assumed it was one of you guys :)

**Comment by faceleg** [comment]
I think we can rest assured that NuGet updates have stopped.

Apologies. If anyone has the desire to get them started, reopen the issue.
