### ISSUE TITLE
Problem on closing dialog

### ISSUE THREAD

**Issue by zeldich** [likeastore/ngDialog#383]
I am using ngDialog in our application, I don't succeed to close the open dialog 
dialogModal = ngDialog.open({
                    template: '..',
                    showClose: false,
                    closeByEscape: false,
                    disableAnimation: true

                });
....
dialogModal.close();
...
I noticed that if I uncomment the commented section inside performCloseDialog function (in ngDialog)
the problem is solved.
Need your help ASAP

**Comment by faceleg** [comment]
Is this still an issue?
