### ISSUE TITLE
How to set the width of dialog?

### ISSUE THREAD

**Issue by thienan93** [likeastore/ngDialog#385]
I need to set the width of dialog, each dialog will be set different value. How to do that?. Currently, as I know, the width of dialog is hard-coded in css file.

**Comment by faceleg** [comment]
You might add a class to your dialogs and style that class with css

**Comment by thienan93** [comment]
Thanks for your suggestion. But your suggestion isn't flexible, Suppose I have 100 different dialog I need to add 100 css class. Do you have other way better to do that?

**Comment by faceleg** [comment]
Do you really have 100 different dialogs that all need custom widths?

**Comment by thienan93** [comment]
No I just give me an example to point that your suggestion is not the best way. I need to find other way.

**Comment by faceleg** [comment]
I would argue that is is the best way, *until* you find you have an unmanageable number of dialogs. Be careful not to over architect a solution.

**Comment by ilaipi** [comment]
how to do it ?

![image](https://cloud.githubusercontent.com/assets/1689135/12227108/fc8f1882-b861-11e5-9a4a-03eac5d4218e.png)

the selected div element is my dialog which I can control,

but it is inside `<div class="ngdialog-content" role="document">`
