### ISSUE TITLE
typeError: controllerInstance is not a function

### ISSUE THREAD

**Issue by paddingme** [likeastore/ngDialog#386]
If I use  the controller itself like below, there is a typerError:

```
function ACtrl() {
    var vm = this;

    this.openDialog = function() {
        ngDialog.open({
            template: 'EditOrgsTemplate',
            controller: 'Actrl'
        })
    }
}

```
![snip20151216_1](https://cloud.githubusercontent.com/assets/5771087/11835592/bb7c2616-a40f-11e5-8cab-3fe3aa8b5f8f.png)

I use the previous ngDialog.js  version, It's ok.

**Comment by bsubramanian-a** [comment]
does this bug cleared? I get the same problem

**Comment by faceleg** [comment]
Does it fail if you use `Actrl`, i.e. without the quotes?

**Comment by BarryWaluszko** [comment]
Similar code snippet that should work, tested with ngDialog v0.5.7
(function () {
            'use strict';

            angular
                .module('myApp', ['ngDialog'])
                .controller('MyCtrl1', MyCtrl1)
                .controller('MyCtrl2', MyCtrl2);

            MyCtrl1.$inject = ['ngDialog'];

            function MyCtrl1(ngDialog) {
                this.openDialog = function () {                    
                    ngDialog.open({
                        template: 'firstDialogId',
                        plain: false,
                        controller: 'MyCtrl2',
                        controllerAs: 'vm'
                    });
                }
            }

            function MyCtrl2() {
                this.value = 'test value 2';
            }

        })();

**Comment by ying1248** [comment]
I get the same problem.

**Comment by faceleg** [comment]
Closing, don't think this is a bug.

**Comment by iamakimmer** [comment]
`    ngDialog.open({
        template: 'gallery.html',
        controller: ['$scope', function($scope) {
            
        }]
    });`

Getting same error with even just embedding the controller

**Comment by faceleg** [comment]
Please provide a JSFiddle that displays the problem
