### ISSUE TITLE
Disable autofocus

### ISSUE THREAD

**Issue by JonWallsten** [likeastore/ngDialog#387]
Is it possible to disable autofocus on input? I have a keybord popping up once user is entering a textbox. And I don't want this to be triggered automatically.

**Comment by Tathanen** [comment]
Look for trapFocus in the readme, you'll need to disable it for the modal in question (or globally if you want).

**Comment by Tathanen** [comment]
Alternatively, put an anchor at the start of the modal to receive the focus instead, to preserve the accessibility benefit of trapFocus.  The script focuses the first element that matches this selector:

`a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, *[tabindex], *[contenteditable]`

**Comment by faceleg** [comment]
@JonWallsten see https://github.com/likeastore/ngDialog#trapfocus-boolean
