### ISSUE TITLE
ndDialog close slowly and the html element focus wrong

### ISSUE THREAD

**Issue by flyed** [likeastore/ngDialog#391]
![1](https://cloud.githubusercontent.com/assets/3076501/11973074/129c842e-a990-11e5-8fa8-8e8b7c225160.jpg)
![2](https://cloud.githubusercontent.com/assets/3076501/11973075/12bcf06a-a990-11e5-9107-146eff306659.jpg)

i use the ngdialog as a data select dialog, when i closed it ,the body element cann't get fcous Immediately and if i click the page, some things will  be selected.

**Comment by faceleg** [comment]
Sorry, I'm not quite sure what the issue is here?
