### ISSUE TITLE
It there set dialog width automatic?

### ISSUE THREAD

**Issue by 0604hx** [likeastore/ngDialog#393]
The width of dialog default to 450px.
Sometimes my template is so wide that dialog cannot display complete. I know we can set the dialog class , and then use this style:
.myDialog .ngdialog-content {width:800px !important;}

But I think it not a good deal I need definition many css class.
And is there a better way to fix it ? Thanks a lot.

**Comment by faceleg** [comment]
You could make a custom ngdialog theme - I do not think ngdialog javascipr interferes with CSS width at all.

**Comment by zgyin** [comment]
i have the same quession with @0604hx . i support add interface about width of dialog .customizable and flexible.

**Comment by faceleg** [comment]
Feel free to submit a PR that implements this option
