### ISSUE TITLE
Error: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by claudiolassala** [likeastore/ngDialog#394]
I just followed the simple instructions (added references to js, css, etc.)... the method in the controller looks like this:

function Customers(customersRepo, ngDialog) {
        var vm = this;
        vm.new = function () {
             ngDialog.open({ template: 'newCustomer.html'});
        };
    }

When I run it, I get the following error in the console:
GET http://localhost:8383/playground/newCustomer.html net::ERR_EMPTY_RESPONSE

If I try the following...
ngDialog.open({ template: 'newCustomer.html', plain:true });

I get the dialog showing "newCustomer.htm" string on it...

If I try this:
ngDialog.open({ template: '<div>Whatever...</div>' });

I get this:
GET http://localhost:8383/playground/%3Cdiv%3Eblah%3C/div%3E net::ERR_EMPTY_RESPONSE

What could I be missing?

Thanks in Advance.

Claudio

**Comment by claudiolassala** [comment]
Oh, nevermind that... totally my bad... didn't realize I had to add full path to the template...  :)

**Comment by faceleg** [comment]
:D sorry nobody helped out, but glad you figured it out
