### ISSUE TITLE
Elements with position relative are hidden when they start off screen (need to scroll)

### ISSUE THREAD

**Issue by luisbritescarvalho** [likeastore/ngDialog#397]
Hi,

Using my macbook pro retina screen I cannot see the elements with position relative that start off screen. Strangely, it works on my external screen.  

Example here:
http://plnkr.co/edit/t1NpKantZ0SPtpg3phxG?p=preview

Much appreciated.

**Comment by faceleg** [comment]
Works fine for me. Browser?

**Comment by luisbritescarvalho** [comment]
Google chrome for example. 
Are you also testing on a MBP screen? Because on my external is working fine.

**Comment by faceleg** [comment]
Works fine for me on MBP screen safari and chrome

**Comment by seawenzhu** [comment]
encounter same problem

**Comment by seawenzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/5305068/12443090/40dcb94c-bf90-11e5-89ab-3682a9ce2090.png)

on my MBP , have problem

**Comment by faceleg** [comment]
What about safari? Have you tried with all chrome extensions turned off?

**Comment by seawenzhu** [comment]
There is no problem on safari.

**Comment by faceleg** [comment]
As I can't replicate this at all, closing. Reopen if you find evidence that ng dialog is at fault
