### ISSUE TITLE
Disabling opening more that one dialog of a kind

### ISSUE THREAD

**Issue by edenpessach** [likeastore/ngDialog#400]
I noticed there is no way to prevent a dialog from opening more than one simultaneously (which is not a common case), beside when binding to a button that a user cannot click or adding functionality to prevent opening the dialog to the controller.

Iv'e noticed other people came across this problem like this thread http://stackoverflow.com/questions/28984310/is-it-possible-to-restrict-ngdialog-to-allow-only-one-open-modal/34747113#34747113 , which I responded with a solution.
But this solution must be made for every dialog.

So I took the time and created this pull request #399 which enable users to override a setting in the config phase, causing same name dialogs to be opened once simultaneously. This way users don't loose any functionality, but can use this feature by giving unique names to their dialogs causing them not to open more than once simultaneously.

Following contributor guidelines:
- Added unit tests
- Followed coding style
- Added documentation to readme

How to use:
```
var app = angular.module('exampleApp', ['ngDialog']);

app.config(function (ngDialogProvider) {
    ngDialogProvider.setOpenOnePerName(true);
});
```
```
// dialog opened normally
var first = ngDialog.open({
      name:'upload dialog'
    });

// dialog was not opened. second is undefined.
var second = ngDialog.open({
      name:'upload dialog'
    });
```
Let me know what you think.

**Comment by faceleg** [comment]
There is a PR open for this: #399

**Comment by faceleg** [comment]
Closing this to ensure discussion stays on the PR thread. (#399)

**Comment by miketeix** [comment]
The new ```ngDialogProvider.setOpenOnePerName(true)``` doesn't seem to work for me. I'm still able to trigger multiple modal dialogs layered on top of one another.

```ngDialogProvider.setOpenOnePerName(true)```

```$rootScope.signupModal = Modal.open({
                name: 'signup',
                  ...
            });```

**Comment by miketeix** [comment]
Was having trouble with this, but realized it was my service wrapper that wasn't yet wired up to pass along 'name' opts property. Works great!!
