### ISSUE TITLE
template does not render html file but triggers GET request 

### ISSUE THREAD

**Issue by chrisvel** [likeastore/ngDialog#402]
I am using Rails and `angular-rails-templates` gem. My project structure keeps my template files in `app/assets/javascripts/templates` and my angular project in `app/assets/javascripts/angular-app`. I have set up ng-modal as:
```
$scope.callModal = function () {
      ngDialog.open({
          template: 'tickets/partials/_resolve.html',
          controller: 'TicketEditController',
          scope: $scope
     });
 };
```

I have a template called `_resolve.html.erb` inside my `app/assets/javascripts/templates/partials/_resolve.html.erb`. The issue is that whenever I press on the button who `ng-click` the function, I see a GET request to `/tickets/partials/_resolve.html` so it doesn't actual render the template but just makes an http request to that uri. 

The modal pops up but displays the whole root page (not the template). 

Is this the default behaviour? And If no, how can I make this work?

**Comment by faceleg** [comment]
templateUrl?

**Comment by faceleg** [comment]
Angular will attempt to GET whatever URI you have entered as the `template` property's value.

If you actually mean `whatever.html.erb`, then you can try writing that instead.

**Comment by ashish-agarwal24** [comment]
I am getting the same issue?
