### ISSUE TITLE
ngDialog button element dismissed if the element not in window visible area

### ISSUE THREAD

**Issue by seawenzhu** [likeastore/ngDialog#405]
ngDialog button element dismissed if the element not in window visible area
![image](https://cloud.githubusercontent.com/assets/5305068/12441749/50bdfaa2-bf85-11e5-8e1e-9d34d70c02d6.png)

and after mouse hover the element, then it displayed again
![image](https://cloud.githubusercontent.com/assets/5305068/12441766/7ba8b766-bf85-11e5-88e2-c78e4248f366.png)

**Comment by faceleg** [comment]
can you replicate this in a minimal jsfiddle or plunk?

**Comment by imsandli** [comment]
I have similar issues with, but only with MDL. And I'm only able to reproduce it on Chrome (Inspect -> mobile view) or on a Android phone/Tablet with Chrome.

Here is a [plunk](http://embed.plnkr.co/YlRtyJ/)

**Comment by mvarrieur** [comment]
I've had the same issue. Only in Chrome. Works perfect in Firefox. I've been trying to get a working plunker or jsfiddle with no luck but the general gist of it:

Create an ngdialog that is draw longer than the viewport with <button> elements (not sure on other element types, this is the only one I've seen it with.

Scroll down to where the button is, it will not be visible until you mouseover it (and sometimes not even then)

I could potentially spin up another version of my app and create some test logins if that would be helpful. (My app is login only unfortunately and I don't have a dummy data account right now)

**Comment by alivesay** [comment]
Same thing happens for me under Chrome on Android (though not Chrome on Windows!).

**Comment by maxpapezhuk** [comment]
Same issue for me under Chrome on Android

**Comment by seawenzhu** [comment]
This is chrome bug, when css position:fixed. 

but I don’t know how to fix this yet.

**Comment by alivesay** [comment]
There's some possible workarounds here: http://stackoverflow.com/questions/11258877/fixed-element-disappears-in-chrome

And this chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=288747

**Comment by mvarrieur** [comment]
I've tried these fixes before and none worked for me in this specific situation. Let me know if they work for you guys tho I'd love to know which ones specifically.
