### ISSUE TITLE
Make popin close on backspace

### ISSUE THREAD

**Issue by Tiagojdferreira** [likeastore/ngDialog#406]
When you return to the previous page using backspace, the popin does not close. Since in my project I do not want to change the library directly, I will use angular on my controller, to close the popin, however it would be a nice addition to either make the closebyEscape also react to backspace:
````
(event.keyCode === 27 || event.keyCode === 8)
````
Or to implement a closeByBackspace boolean.

I can implement this feature if you want me to. Which way should I do it ?

**Comment by Tiagojdferreira** [comment]
Another interesting functionality would be to add closeByPopstate, that would allow to close the popin when you click on the go back button of the browser.

Once again, if you want me to, I can take a look at it and make a PR

**Comment by faceleg** [comment]
I dealt with this by closing the dialog inside the `$destroy` event of the relevant controller.

I would have appreciated a `closeByPopState` though. If you've the time and inclination to submit a PR that adds this, great!

I'd like it if it fired when:

 - User presses back
 - User performs an action that causes `history.back()`
 - JavaScript code causes `history.back()`, e.g. someone uses ui-router's services to go back.

Also unit tests.

**Comment by Tiagojdferreira** [comment]
It seems that closeByNavigation causes the protractor tests to fail. It is as though something in protractor is causing the state to change. I will let you know if I manage to find out why this happens and fix the tests.

**Comment by Tiagojdferreira** [comment]
The parameter closeByNavigation does just what we need it to do, so in my PR I set it to true by default and added some doc. Unfortunately, it seems that protractor interferes with it through $locationChangeSuccess.
