### ISSUE TITLE
close(id) closing all others dialogs anyway

### ISSUE THREAD

**Issue by asso1985** [likeastore/ngDialog#407]
ngDialog.close('ft-modal-loading');

Is closing all others modals.

**Comment by faceleg** [comment]
Was it a bug?

**Comment by asso1985** [comment]
Nope, but i think that the Id property is not clear. In the docs you should
put It clear that the ID is not tge one you define but the returned one
Il 21 gen 2016 8:32 PM, "Michael Robinson" <notifications@github.com> ha
scritto:

**Comment by faceleg** [comment]
We would greatly appreciate a pr that updated the documentation to make his more clear.

**Comment by asso1985** [comment]
I Can help if needed, surely

2016-01-22 10:45 GMT+01:00 Michael Robinson <notifications@github.com>:

**Comment by nicogaldo** [comment]
Not working for me, also all modal windows are closed. This is my button inside of template:
`<button ng-click="close({{ngDialogData.ngDialogId}})" ...`
