### ISSUE TITLE
Resolve ngDialog box with http response content

### ISSUE THREAD

**Issue by madhavan020985** [likeastore/ngDialog#409]
I open a dialog box as,
````
var prom = ngDialog.open({      template: 'dialog',
      scope: $scope
    })
````
Once the dialog box is opened, user selects a menu item and presses Ok button. Ok button triggers a http request with the selected input as post body param.

Now, i must resolve the dialog box's `prom` promise asynchronously with the http response value.

I have tried resolving the dialog's promise as `closeThisDialog('Some value')` and it works successfully but not sure how i can resolve it with a async response value.

**Comment by madhavan020985** [comment]
Instead of resolving the dialog box's promise, i changed the parent scope object directly in $http callback... And it works. Closing this issue, thanks.

**Comment by faceleg** [comment]
:dancer:  thanks for reporting your resolution back, this will likely help a future user.
