### ISSUE TITLE
Open ngDialog the second time failes 

### ISSUE THREAD

**Issue by bnbarak** [likeastore/ngDialog#410]
The function which opens the ngDialog is:
```angular
$scope.editArticle = function (article, cats) {
      $scope.editArticle = article;
      $scope.dialog = ngDialog.open({            
        template: 'editArticle',
        data:{
          'article': article,
          'cats'   : cats
        },
        controller: 'articleActionController',
        closeByEscape: true
        
      });
    }; 
```

The first time the function is running it works. The second time, after closing the modal, I receive the following error:
#TypeError: v2.editArticle is not a function 

I'm using MEAN.js.

Thank you.

**Comment by simonghales** [comment]
Why do you set $scope.editArticle twice?

The first time you set $scope.editArticle to be a function, which opens up the dialog.
But immediately in that function you set $scope.editArticle again, this time to be the passed in article. There's some kind of recursive issue there. As the next time you try to call $scope.editArticle(); $scope.editArticle is now set to whatever article object you passed through in the function.

Would removing `$scope.editArticle = article;` fix the problem?

```
$scope.editArticle = function (article, cats) {
      $scope.dialog = ngDialog.open({            
        template: 'editArticle',
        data:{
          'article': article,
          'cats'   : cats
        },
        controller: 'articleActionController',
        closeByEscape: true

      });
    }; 
```
