### ISSUE TITLE
Unable to update view (using $scope) when i provide template and use Plain: false

### ISSUE THREAD

**Issue by omairkhan** [likeastore/ngDialog#412]
Hi,

I am facing problem and struck due to that. I am using code:
where, 
controller name : AteaProfile,
and inside, var vm= this;

 var dialog = ngDialog.open({
                    template: 'changeMobileNumber.html',
                    controller:'AteaProfile',
                    className: 'ngdialog-theme-plain',
                    closeByDocument: false,
                    data: vm
                 });

behind the scene when user click save button it takes value in that function, but doesn't update the view. 
I have tried various solutions 
by removing controller, 

by place scope: $scope , with/without it.

but the view is unable to update.
can you please give me solution quickly? 

Thanks..

**Comment by faceleg** [comment]
Please use stackoverflow.com for general programming problems.
