### ISSUE TITLE
how can i give a spicific name to dialog when ngDialog.open called

### ISSUE THREAD

**Issue by Sky-Li** [likeastore/ngDialog#418]
i use the option.name like this, but the dialog still be named "dialog1". Hope for any help,thx
```
ngDialog.open({
            template: './pages/package-flow/kit-detail-dialog.html',
            className: 'ngdialog-theme-default',
            scope: $scope,
            name: "kit-detail-dialog",
            cache: false,
            showClose: false
        });
```

**Comment by faceleg** [comment]
https://github.com/likeastore/ngDialog#name-string--number should be the way to do it, if this isn't working then sounds like bug.

How do you mean "still names dialog1" though? Are you sure "dialog1" isn't the id?

**Comment by Sky-Li** [comment]
'ngdialog1(/2/3)' is the default id, and i hope i can give dialog a spicific id. 
So i use **option.name**.
And then i failed, did i misunderstand the usage of name?

**Comment by faceleg** [comment]
ID is for internal use, why do you need to set ID?

**Comment by flashjammin** [comment]
I am having a similar problem. I have a dialog that when the user clicks a button it opens a second dialog. When I want to close the second dialog I am using ngDialog.close() and it closes both dialogs, I need to give it a specific id, that is known to me, so that I can call .close("specificId").

When I call ngDialog.open() I give it a name and an id however these do not seem to get put on to the dialog in the DOM

Example in this plunker http://plnkr.co/0bg1VB7QuEZxIdakfoBr

**Comment by faceleg** [comment]
Sorry I tried to look at the plunkr but I'm too tired to quickly understand what is going on. If you want me to help with that one please condense it so the JS is all in one file.

I still don't think you need to set an id, the return value of open should be sufficient: https://github.com/likeastore/ngDialog#returns

**Comment by flashjammin** [comment]
The main issue I am having is that the id is not being set on the dialog div, there is also a few other options that do not seem to be working as expected...
appendClassName and name

`scope.openCustomDialog = function() {
	ngDialog.open({
		template: "customDialog.html",
		closeByDocument : false,
		name: "custom-dialog",
		appendClassName: 'custom-dialog',
		scope: scope
	});
};`

![image](https://cloud.githubusercontent.com/assets/7479498/14162622/02744f98-f74a-11e5-842c-1c4adb6a0cc9.png)

As you can see its coming through

**Comment by flashjammin** [comment]
I have realised what my issue is, I am using version 0.5.6 which does not support appendClassName...sorry, my mistake.

**Comment by faceleg** [comment]
No problem, thanks for coming back with the solution :)
