### ISSUE TITLE
Update to work with angular 1.5.0

### ISSUE THREAD

**Issue by faceleg** [likeastore/ngDialog#422]

**Comment by JuanAntelo** [comment]
I am unable to make ngDialog work with angular1.5 as well

**Comment by tjwudi** [comment]
Could you describe what issue you are having with 1.5.0? I could use it with 1.5.0 seamlessly.

**Comment by faceleg** [comment]
Tests broke when I ran them with 1.5.0

**Comment by PhiLhoSoft** [comment]
Which tests, @faceleg? Yours, or ngDialog's ones?
As said by @tjwudi, I was able to run ngDialog with 1.5.0 without issues.
I suggest you report what tests are broken (if they are ngDialog ones), what error messages you have, etc.

**Comment by ArniDzhan** [comment]
@PhiLhoSoft @tjwudi how did you guys even install it? There is a conflict which requires interactive mode which makes it not usable when deploying.
Or am I missing something?

**Comment by PhiLhoSoft** [comment]
"_which requires interactive mode which makes it not usable when deploying_"
Not sure why you say it makes it not usable. If you talk about Bower, you can ask it to save the resolved conflict / dependency, and then it passes automated builds in Jenkins and al.

**Comment by ArniDzhan** [comment]
@PhiLhoSoft thnx for hint, I didn't know you could do that.
adding this to bower.json did it
````json
  "resolutions": {
    "angular": "1.5.0"
  }
````

**Comment by faceleg** [comment]
@PhiLhoSoft Travis was broken
I specified 1.4.9 in bower.json, pushed
Travis was fixed

I didn't look into it any further than that due to time constraints. If you would submit a PR that forces 1.5.0, we can see how that build goes.
