### ISSUE TITLE
Dialog doesn't show up in the center of the screen and is behind the overlay

### ISSUE THREAD

**Issue by aseemflowingly** [likeastore/ngDialog#425]
I have a simple ngDialog with external template. But it ends up showing right at the top of the screen and behind the overlay.

How can I get it to show at the center of the screen and as a proper modal dialog?

Plunkr: http://plnkr.co/edit/Vvh9Z7C5mDnspu8aQHEh?p=preview

**Comment by aseemflowingly** [comment]
Seems like you need the class name to be "ngdialog-theme-default" or something which is a proper theme.

**Comment by faceleg** [comment]
This got me as well at first.

If you had the time/inclination to update the docs to be more clear on this please PR!

**Comment by aseemflowingly** [comment]
@faceleg :  I have added a couple of lines to the readme and submitted a PR.
