### ISSUE TITLE
Support for additional class that doesn't override defaults

### ISSUE THREAD

**Issue by JulianLaval** [likeastore/ngDialog#434]
Hi there!

For the time being, specifying a `className` on `ngDialog.open()` overrides any defaults set previously. This is particularly frustrating, as it prevents one from appending a new class specific to the dialog being opened to the defaults.

I'm wondering whether it would make sense to support an extra property, such as `extraClass`, that merely appends a class to the defaults instead of overwriting them, e.g.

```
ngDialogProvider.setDefaults({
    className: 'ngdialog-theme-default ngdialog-theme-custom'
});
```
and
```
ngDialog.open({
    template: 'xxx',
    extraClass: 'feedback-success-dialog'
});
```
would add all three classes to a newly opened dialog.

Looking through `ngDialog.js`, this seems like it would take no more than a few lines to support the additional parameter.

Thoughts? Am I suggesting something that is already supported?

Cheers!

**Comment by faceleg** [comment]
I would prefer it be called `appendClassName`.

Aside from that I am open to a PR that has accompanying unit tests. 

@voronianski, @egor-smirnov what are your thoughts?

**Comment by JulianLaval** [comment]
Definitely agree with `appendClass` or `appendClassName` as the property name.

I already have it running on a local clone - happy to submit a PR if @voronianski and @egor-smirnov think it's a good idea!

**Comment by faceleg** [comment]
Submit the pr and mention this issue in a comment, that way when they get these emails they will have something more to look at. :)

**Comment by faceleg** [comment]
I say appendClassName as it matches the className option.

**Comment by JulianLaval** [comment]
Sounds good, will submit PR!
