### ISSUE TITLE
Browser Back Button ngRoute

### ISSUE THREAD

**Issue by stephenycchang** [likeastore/ngDialog#438]
I see the example with the ui-router. Trying to implement this using ngRoute. 

My route: 

  `.when('/home', {
     templateUrl: 'foo',
     controller: 'fooCtrl',
     reloadOnSearch: false})`

My Controller: 
  `$scope.openFileInDialog = function(fileForDialog) {
      $scope.currentFile = fileForDialog;
      $location.search('resource_id', fileForDialog.id);
      var openDialog = ngDialog.open({
        template : 'views/poo.html',
        controller : 'pooCtrl',
        "scope" : $scope
      }); });`

I've also set closeByNavigation to true on default. 

So when I click to trigger the dialog, the url appends to the browser correctly the first time. And the states change correctly, however, on second click of an item on page rendered by `ng-repeat` , I receive an error:

`TypeError: Cannot read property 'trapFocus' of undefined
    at Object.privateMethods.activate (ngDialog.js:97)
    at ngDialog.js:605
    at angular.js:18744
    at completeOutstandingRequest (angular.js:5804)
    at angular.js:6081`

Without the `$location.search` line, it works perfectly. However, my confusion is that I'm passing in the same thing to the dialog, so what could possibly be undefined?

Any guidance would be appreciated! Thanks!

**Comment by faceleg** [comment]
Would you be able to put together a plunkr that shows the issue?

**Comment by stephenycchang** [comment]
@faceleg I got it to work fine after setting a $timeout on the ngDialog function, allowing the $location.search to trigger first. It was just where the cycle was triggering. 

Thanks

**Comment by faceleg** [comment]
OK, thanks for coming back with that.

Should I close this issue?
