### ISSUE TITLE
Preventing body from shifting when opening/closing popup.

### ISSUE THREAD

**Issue by miguelleite** [likeastore/ngDialog#44]
When triggering the popup, when it gets shown, the body content shifts around 20px (i believe it's the scrollbar width equivalent). The same happens when closing. It also happened with bootstrap, but was fixed in version 3.2.0 of it.
Does anyone have a solution for this?
It's not a blocker but it really affects ui/ux appearence.

Thanks in advance.

**Comment by mk-lviv** [comment]
Also waiting for fix

**Comment by ben-crowhurst** [comment]
+1
