### ISSUE TITLE
Change dependencies

### ISSUE THREAD

**Issue by petkostas** [likeastore/ngDialog#441]
Currently angular dependencies in ngDialog bower.json are set to "**1.4.9**", this is failing with packages requiring the latest stable version of the **1.4.x** (1.4.10 currently). Although you can overcome this with manual resolving the situation, this is not the case with packages such as Django bower, which can install without user interaction and widely used for deployment.
Dependencies should be changed to "**~1.4.10**"

**Comment by faceleg** [comment]
Out of interest, what are the implications for things like Django bower if we bumped the angular version to 1.5.0?

**Comment by petkostas** [comment]
You would be forcing users to use the 1.5.x branch, although considered stable, there are many changes in the 1.5 release and many large projects have not moved to it yet.
You could introduce a minor and larger version check as `"angular": ">=1.2.15 <1.6",`

**Comment by faceleg** [comment]
That's a good suggestion.
