### ISSUE TITLE
preCloseCallback() cannot get a variable created in ngDialog's scope controller

### ISSUE THREAD

**Issue by alainib** [likeastore/ngDialog#446]
**What version of ng-dialog are you using?**
v0.5.8
**What version of AngularJS are you using?**
1.5.1
**What browsers are affected?**
mozilla chrome
**Please provide either a JSFiddle, Plunkr example that replicates the issue**
I cannot replicate the issue with a simple example.

**Please describe the issue**
 
[I made a stackoverflow question her](http://stackoverflow.com/questions/36082443/angularjs-ngdialog-isolate-her-scope-instead-of-sharing-it-with-parent)

The problem i have is : 
If i made change in ngDialog controller on $scope.variable, this change are not available in the precloseCallback or in my original controller where these variable are declared ! I try for example to create a simple variable like `$scope.test = 'ok';`, it is undefined in the `preCloseCallback`

**What did you expect to happen?**
How to edit a $scope.variable in ngDialog controller and get this change in preCLoseCallback ?
What i'm making wrong ?

**What actually happened?**
All the change made in ngDialog controller  are unavailable in preCLoseCallback  or in my original controller where these variable are declared ! . It is like he get a copy of the scope when the ngDialog.open(...)

I'm stick, any advice are welcome. thanks

**Comment by alainib** [comment]
I found a way to make it work but i can get why i work now and not before.
I cut all the function ( not the variable declaration ) form the ngDialog's controller and paste them in the parent controller. now it work strangely

**Comment by faceleg** [comment]
I'll close this, keep an eye on your SO post, we can't provide technical support like this here.

re-open if you find a bug.

**Comment by alainib** [comment]
did you now why this happen ? i have to move all the functions from the ngdialog controller to outside the ngdialog to make it work

**Comment by faceleg** [comment]
No idea, and as I don't think it is a bug in ngdialog, I unfortunately don't have time to look into it. Hence my comment about SO.
