### ISSUE TITLE
closePromise does not fire in IE11

### ISSUE THREAD

**Issue by anvarjmc** [likeastore/ngDialog#448]
**"ng-dialog": "~0.5.6"**

** "angular": "1.4.0"**

**IE11 with no developer tools**

**Invoking closeThisDialog as "$scope.closeThisDialog(true);" and  expecting a promise to be returned.

ngDialog.open({
                    templateUrl: 'Some.html',
                    controller: 'SomeCtrl',
                    data: data
                }).closePromise.then(data=> {
                    if(data.value === true){
                       //update data
                    }
                });
**

**Expecting a dataset to be updated after closing the dialog in IE 11**

**It returns promise only if the "F12 Devloper tools" enabled, otherwise it is not giving promise. **

**Comment by faceleg** [comment]
Please provide information for each of the points noted in the issue template

https://github.com/likeastore/ngDialog/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by anvarjmc** [comment]
It seems, this is relevant to Tomcat when you deploy wepapi and angular app together, hence closing it.. But I just prepared a sample use case for ngDialog which could be helpful for somebody.

**What version of ng-dialog are you using?**
ng-dialog  = 0.5.6
**What version of AngularJS are you using?**
AngularJS : 1.4.0
**What browsers are affected?**
IE without enabling developer tools
**Please provide either a JSFiddle, Plunkr example that replicates the issue**
https://plnkr.co/edit/f2hpqXJdeciHXWO6dFoB
**Please describe the issue**
After closing the dialog, I am expecting a closePromise back to the calling place with a status.
**What did you expect to happen?**
closePromise should be returned and the status should be ‘True’
**What actually happened?**
closePromise did not return and the status appeared as ‘False’. It is working if I enable developer tools.
