### ISSUE TITLE
ng-dialog not rendering UI outside viewport

### ISSUE THREAD

**Issue by ksgupta** [likeastore/ngDialog#449]
**What version of ng-dialog are you using?**
0.5.5
**What version of AngularJS are you using?**
1.3.0
**What browsers are affected?**
Chrome
**Please provide either a JSFiddle, Plunkr example that replicates the issue**

**Please describe the issue**
I have this strange UI issue using ng-dialog in my application. The UI outside initial UI that is not visible at the launch of the dialog, is not loaded automatically on scrolling down in the dialog screen.

**What did you expect to happen?**
The UI elements outside the viewport should be properly rendered and visible without need of manual interaction.

Screen view after: Dialog opens --> Scroll Down -> Scroll Up again
<img width="1042" alt="screen shot 2016-03-30 at 14 20 22" src="https://cloud.githubusercontent.com/assets/6197427/14157782/8993d8f0-f681-11e5-9a83-7ec82d4815b5.png">

**What actually happened?**

Screen view after: Dialog opens --> Scroll Down -> Scroll Up again -> Clicking on invisible text input box.
<img width="1021" alt="screen shot 2016-03-30 at 14 20 54" src="https://cloud.githubusercontent.com/assets/6197427/14157783/899456c2-f681-11e5-990c-ce60f60dc765.png">

I need to click on the elements to make them visible in the UI. Same way when I scroll up, the previously loaded UI elements are invisible and I have to click on them to make them visible.

I feel this is the case of loading UI elements only when they are patr of the viewport; however I am not sure how fix this bad user experience.

Any help on how to fix this appreciated.

**Comment by randyhoulahan** [comment]
I have the same issue.

**Comment by faceleg** [comment]
Please provide either a JSFiddle, Plunkr example that replicates the issue

**Comment by jcieslak** [comment]
+1 same problem here

**Comment by faceleg** [comment]
Please provide either a JSFiddle, Plunkr example that replicates the issue

**Comment by chungconscious** [comment]
I was having the same issue and came across this blog:
http://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css

Short answer: add the CSS below (if you're using default theme)


```
.ngdialog.ngdialog-theme-default .ngdialog-content {
  -webkit-transform: translateZ(0);
  -moz-transform: translateZ(0);
  -ms-transform: translateZ(0);
  -o-transform: translateZ(0);
  transform: translateZ(0);

  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  -ms-backface-visibility: hidden;
  backface-visibility: hidden;

  -webkit-perspective: 1000;
  -moz-perspective: 1000;
  -ms-perspective: 1000;
  perspective: 1000;
}




```

**Comment by miguerpwork** [comment]
It works!! thank you @chungconscious

**Comment by faceleg** [comment]
Closing as nobody provided a JSFiddle or something else replicating the issue.

**Comment by tjsail33** [comment]
Also experiencing this issue, however it is in a proprietary piece of code that i cannot export to a plunkr due to IP rights. Seems to be a Chrome only issue based on internal testing. I know this isn't terribly helpful, but this problem still exists.

Angular 1.5.9
ngDialog 0.6.2
