### ISSUE TITLE
Pass a directive as template value

### ISSUE THREAD

**Issue by Tibicenas** [likeastore/ngDialog#450]
"ng-dialog": "^0.5.8"
"angular": "^1.5.0",

I want use a directive or a component instead of a template
```javascript
ngDialog.openConfirm({
	templateUrl       : 'someFolder/SomeSubFolder/mytemplate.html',
	closeByNavigation : true,
})
```
Something like this, but i don't see in the DOC how to do that
```javascript
ngDialog.openConfirm({
	template          : '<my-directive></my-directive>',
	closeByNavigation : true,
})
```

**Comment by faceleg** [comment]
Try using the `plain` option: https://github.com/likeastore/ngDialog#plain-boolean

```JS
ngDialog.open({
    template: '<p>my template</p>',
    plain: true
});
```

**Comment by Tibicenas** [comment]
Perfect ! just need the plain: true   :+1:   thanks you man !
