### ISSUE TITLE
scrolls top 0 when closed

### ISSUE THREAD

**Issue by vgiacchina** [likeastore/ngDialog#452]
Hi all,
i'm using the last ng-dialog version.
I have a problem when i close (tap on ngdialog-close). the window scrolls to top 0.
I tried everything.

**Comment by vgiacchina** [comment]
the problem was height:100% in html. 
.ngdialog-open{
  height: auto !important;
}
now it works.
tnx

**Comment by faceleg** [comment]
Thanks for letting us know the solution.

Does this require a change in ngDialog, or was it caused by your local styles?

**Comment by meoz** [comment]
Same problem here. Does anyone has a fix ?

**Comment by faceleg** [comment]
I don't have this problem and I haven't seen it proved with a JS Fiddle. 

If you are able to provide an example case in JS Fiddle that shows this issue please post it here and I will look at reopening this issue.

**Comment by caohongtao** [comment]
@meoz I encountered this problem when I set  height:100% to <html>.
@vgiacchina 's  solution fix it.
