### ISSUE TITLE
Passing data to dialogs controller without using $scope

### ISSUE THREAD

**Issue by dirkmanske** [likeastore/ngDialog#454]
**What version of ng-dialog are you using?**
0.6.0

**What version of AngularJS are you using?**
1.5.5

**Please describe the issue**
I use controllerAs and try to avoid using $scope in my application. I am wondering if is possible to pass data to the dialogs controller without using $scope at all. I hoped that data would fit but it is only accessible via $scope. I also tried resolve but without success. Does resolve work with controllerAs?

**Comment by faceleg** [comment]
I use `controllerAs` and `resolve` extensively. 

Please provide a JSFiddle demonstrating them not working as expected.

**Comment by dirkmanske** [comment]
It was my mistake. It works as expected.

**Comment by faceleg** [comment]
Thanks for reporting back!
