### ISSUE TITLE
closeThisDialog() not working when I send scope

### ISSUE THREAD

**Issue by seandcoleman** [likeastore/ngDialog#455]
I have a page with an object that I want to modify via NgDialog.  I have a button on this page that I attach the dialog controller to.  I via the dialog controller am sending scope: $scope which successfully is connecting to my object. 

However the button in the dialog modal I have is calling a function of the other controller and I am trying to call closeThisDialog();

Example
dialog controller:
 .controller('modalCtrl', ['$scope', 'ngDialog',
       function ($scope, ngDialog) { 
            ngDialog.open({ template:'/mypath/modalTmpl.html', className: 'ngdialog-theme-default', scope: $scope});

}

modalTmpl.html:
```

<div class="row">
    <select.....></select
    <button ng-click="otherController.addToObject(selectedItem) && closeThisDialog(1)">ADD</button>
<div>

```

ng-dialog: ^0.5.8
AngularJS: 1.4.8
browsers: Chrome, firefox

Did I just miss something?

**Comment by faceleg** [comment]
I have no idea.

You can either:

 - Create a JSFiddle that shows the problem if you want help figuring out what is going on
 - Debug it by putting `{{ this }}` in your template to see what is available on the scope.

**Comment by seandcoleman** [comment]
Thank you.  I was able to debug with {{this}}  Great call.

**Comment by faceleg** [comment]
Glad it helped! In case you don't know it, this is also good: https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk?hl=en
