### ISSUE TITLE
In the browser, why when ngDialog.open () that could not bounce too long scroll box operation, click your browser's scroll bar does not work

### ISSUE THREAD

**Issue by smart-dream** [likeastore/ngDialog#457]
"jquery": "^2.1.4",
    "angular": "^1.4.5",
    "angular-sanitize": "^1.4.5",
    "bootstrap": "^3.3.5",
    "extras.angular.plus": "^0.9.2",
    "font-awesome": "^4.3.0",
    "moment": "^2.10.3",
    "angular-ui-router": "^0.2.15",
    "toastr": "^2.1.1",
    "angular-animate": "^1.4.5",
    "angular-local-storage": "~0.2.3",
    "ng-dialog": "~0.5.6",
    "angular-resource": "~1.4.8",
    "ng-file-upload": "~10.1.9",
    "angular-ueditor": "*",
    "angular-socialshare": "~1.4.4",
    "angular-ui-tree": "~2.13.0",
    "angular-bootstrap": "~1.1.0",
    "ng-img-crop": "ngImgCrop#~0.3.2",
    "animate.css": "~3.5.1",
    "angular-clipboard": "~1.3.0",
    "angular-link-header-parser": "~1.0.2",
    "file-saver.js": "~1.20150507.2"

**Comment by faceleg** [comment]
Feel free to reopen if you are willing to fill in the required fields.
