### ISSUE TITLE
How to communicate between it's parent controller?

### ISSUE THREAD

**Issue by elvis-macak** [likeastore/ngDialog#458]
**What version of ng-dialog are you using?**
0.6.0

**What version of AngularJS are you using?**
1.4.9

**What browsers are affected?**
Chrome v50

**Please provide either a JSFiddle, Plunkr example that replicates the issue**
http://plnkr.co/edit/g83i5npfShrdIDlNFs04?p=preview

**Please describe the issue**
I want to open a dialog to edit the content that stores in the parent controller, and after submit, the parent controller's content should also be changed.

In the normal case,  I've to inject the `$scope` both into ParentController, ChildController, and change the variable bind to the Controller.  Think this is not elegant in `controllerAs` scenario.

As the code above,
1. I've to inject `$scope` in both controllers
2. I can only access the controller like this, this code looks ugly

**What did you expect to happen?**
I'd like to add a parentController to the `ngDialog.open` function and can access the parent's data directly.

BTW, the data is used as a json-string that lost the reference to its parent controller variable, it can only used to pass a config data, but cannot return back the data to it's parent.

**Comment by faceleg** [comment]
You can return data back using the `closingPromise` property of the `ngDialog.open` call. https://github.com/likeastore/ngDialog#closepromise-promise

You can use `resolve` (like you have to do with routes) or `data` to pass data to a dialog.

Your two controllers should not be as closely tied as you describe.

**Comment by jasonspick** [comment]
@faceleg in the current version data passed from close() comes back as undefined in the closingPromise

**Comment by faceleg** [comment]
@jasonspick it would be great if you could open an issue with a reproduction for this
