### ISSUE TITLE
the width property not working in 0.6.0 release

### ISSUE THREAD

**Issue by and1gio** [likeastore/ngDialog#462]
**What version of ng-dialog are you using?**
0.6.0

**What version of AngularJS are you using?**
1.5.0

the width not working. 

example from the documentation. but in the release 0.6.0 there is not implemented that feature [width: property]
```javascript
ngDialog.open({
    template: 'template.html',
    width: 400
});
```

**Comment by faceleg** [comment]
I've just rebuilt the min file and published 0.6.1, try again.
