### ISSUE TITLE
I would like to know if you can add the function to drag the form!

### ISSUE THREAD

**Issue by qq645381995** [likeastore/ngDialog#464]
I would like to know if you can add the function to drag the form!

**Comment by faceleg** [comment]
This has been asked before: https://github.com/likeastore/ngDialog/issues?utf8=✓&q=is%3Aissue+drag+

**Comment by faceleg** [comment]
If you're interested in making ngDialog pluggable and implementing a drag and drop plugin, see: https://github.com/likeastore/ngDialog/pull/413

Draggable dialogs will not be implemented in core.

**Comment by introspection3** [comment]
@faceleg you are not wise, the moveable function  is too important for every one ,no body can surpport it ,but only you!
