### ISSUE TITLE
ngDialog  ignore NG attributes in directives and components

### ISSUE THREAD

**Issue by HectorLS** [likeastore/ngDialog#473]
Hi, i have this call inside a controller
Directive

``` javascript
ngDialog.openConfirm({
        template          : '<form-directive></form-directive>',
        plain             : true,
        closeByNavigation : true,
        scope             : $scope
      })
      .then(function( response ) {
          $log('SENDED');
      });
```

Component 

``` javascript
ngDialog.openConfirm({
        template          : '<form-component></form-component>',
        plain             : true,
        closeByNavigation : true,
        scope             : $scope
      })
      .then(function( response ) {
          $log('SENDED');
      });
```

HTML for both

``` html
<form ng-submit="alert("Hello !!!")">
   <button type="submit">Send</button>
</form>
```

When i click the Button on directive, i see the **SENDED** message on the console, but for components
just looks like **ignore everything,** clicks on the button do nothing, but the close button works perfect.
And load the template rightfully

Same template, same everything,
Is exactly the same, so maybe is a ngDialog kind of bug with the components right ?

[Plunkr Issue](http://plnkr.co/i0TKxjTERQpxMjD6L4ph)

The Directive also fail if i use the scope: { obj : '=' }    property inside it
The components ignore everything.

I think is some kind of problem with the Scopes
- The scope declaration in the directive ( or the binding in the component ) 
- And the scope in the openDialog object

**Comment by faceleg** [comment]
I'd be grateful if you added some tests proving this and submitted a PR with a fix!
