### ISSUE TITLE
after closing dialog, page is going to top in chrome browser

### ISSUE THREAD

**Issue by harshbaba** [likeastore/ngDialog#474]
after closing dialog, page is going to top in chrome browser, it is working fine in mozilla and other browsers

**Comment by tgonl** [comment]
Try to put this in your `.css` file

```
.ngdialog-open{
    height: auto !important;
}
```

**Comment by harshbaba** [comment]
thanks bro,
problem fixed.

**Comment by alexkhismatulin** [comment]
if @telmogh's answer doesn't help, try adding 
```
.ngdialog-open {
    height: auto !important;
    overflow: inherit !important;
}
```
