### ISSUE TITLE
NPM module update

### ISSUE THREAD

**Issue by cirocfc** [likeastore/ngDialog#476]
**What version of ng-dialog are you using?**
0.6.2

**What version of AngularJS are you using?**
1.2.13

**What browsers are affected?**
All

**Please describe the issue**
Angular 1.2.x was incompatible with ngDialog, so we corrected this problem in this PR: https://github.com/likeastore/ngDialog/pull/468

**What did you expect to happen?**
Release a new version

**What actually happened?**
Still there's no update on npm.

@negherbon

**Comment by voronianski** [comment]
@cirocfc published latest `0.6.2` to npm

**Comment by cirocfc** [comment]
@voronianski thank you so much man!
