### ISSUE TITLE
Is there the possibility to load the template with ajax?

### ISSUE THREAD

**Issue by GiacomoK** [likeastore/ngDialog#485]
Hi,
I would need to load the template with ajax, is it possible?

Thanks.

**Comment by macintosh-krug** [comment]
Hello. Try to open dialog in AJAX success-callback and use response data as code of template.
[https://github.com/likeastore/ngDialog#plain-boolean](url)

**Comment by GiacomoK** [comment]
It worked like a charm, thanks.
