### ISSUE TITLE
controllerAs,  controllers and scope

### ISSUE THREAD

**Issue by jmls** [likeastore/ngDialog#489]
I am confused about the relations between the above : I am using controllerAs to remove the need to pass $scope around - so how do I pass some data into the controller(as) without using $scope ?

**Comment by tsears** [comment]
set the controller to a function that returns the current controller -- e.g. controller: () => { return this; }

Plunker:
https://plnkr.co/edit/2sjXCiWKicF0og41vkVw?p=preview
