### ISSUE TITLE
Non-modal and draggable dialogs

### ISSUE THREAD

**Issue by marcuswhit** [likeastore/ngDialog#49]
Correct me if these features are already possible, but I need some of my dialogs to be draggable, and non-modal.

Draggable functionality doesn't need to be built into the library, but the issue I'm having is that the top element in my template is draggable, but this element is nested within the created `ngdialog-content` element, meaning that whilst my template is draggable, it doesn't take the dialog with it.  Perhaps if there were an option to replace the element rather than nest the template within it (like Angular directives can), this would be a non-issue?

Would also be nice to have an option for dialogs to be non-modal - i.e. no click-blocker and no blackout effect.  

Great library otherwise, very simple and effective!

Thoughts?

**Comment by egor-smirnov** [comment]
You could disable overlay (or "blackout effect" as it's defined in issue description) by using `overlay: false`.
As already mentioned, playing with `closeByDocument` / `closeByEscape` could be also helpful.
Opening of multiple dialogs is possible - take a look into `examples` folder.

About draggability - feel free to open new issue with live code example on plunker. I am closing this one as it's quite old and covers 2 different topics in one issue.

Thank you.
