### ISSUE TITLE
using ngDialog from within component, $scope does not exist

### ISSUE THREAD

**Issue by pvdh** [likeastore/ngDialog#504]
I'm using ngDialog 0.6.2 with angular 1.5.8, using a component-based architecture. I have a component rendering a list of items and a delete-function. The delete-function is to use ngDialog to have a confirmation popup like "do you realld want to delete item {{name}}?"

My problem: inside a component, $scope simply does not exist. So I'm quite at a loss, passing "name" to the dialog. Is there a workaround? I'm concerned about other details like "In addition .closeThisDialog(value) method gets injected to passed $scope", which might cause further issues?

**Comment by pvdh** [comment]
I suppose http://stackoverflow.com/questions/37650798/ngdialog-ignore-ng-attribute-within-forms-in-angularjs-1-5 is basically the same question.

**Comment by realph** [comment]
+1

**Comment by realph** [comment]
Solved this with the following:

    // My Component's Controller
    class MyComponentController {
      ...

      deleteUser = (user) => {
        // Reference our MyComponentController
        const that = this;

        this.ngDialog.openConfirm({
          template: 'deleteUser',
          controller: function() {
            const vm = this;
            vm.user = that.user;
          },
          controllerAs: 'vm',
          closeByEscape: true,
          closeByDocument: true,
        }).then(
          user => this.UserService.delete(user.id).then(
            () => this.$state.go('users')
          )
        );
      }
    }

**Comment by os-alan** [comment]
The trick here is to setup "bridges" (bindings) between component's isolated scope and external scope where actually ngDialog's injected methods live.

@pvdh provided the link to SO question with the same problem. I have posted more detailed answer there + code example (http://stackoverflow.com/a/41401981/1320558)

**Comment by faceleg** [comment]
Thanks for posting the resolution @realph and the SO post @os-alan
