### ISSUE TITLE
NgDialog 0.6.4: Loop in ngdialog.closing

### ISSUE THREAD

**Issue by tommarien** [likeastore/ngDialog#507]
Likely due to the change in https://github.com/likeastore/ngDialog/commit/90f63150ba6f3de7bbfcdc2795fbf020db6a7f71

We have the following issue: 

We open a dialog, that has a custom listener for ngdialog.closing event: inside the listener we do a ui-router state reload $state.reload.

This cause an infinite loop and makes your browser hang: Chrome, Safari

This is not happening in ngdialog 0.6.2

`
 $rootScope.$on('ngDialog.closing', (e, $dialog) => {
                return this.$state.reload();
        });
`

**Comment by lukaskalcok** [comment]
As this is no longer happening from a version 0.6.2 and the latest version of this package is 1.4.0 is it possible to close this as solved? Thank you. This issue is causing SNYK (https://snyk.io) to mark this package as a DoS problem:

> ng-dialog is a Modal dialogs and popups provider for Angular.js applications. Affected versions of the package are vulnerable to Denial of Service (DoS). 

Thank you.

**Comment by tommarien** [comment]
Closing as requested ;)

**Comment by Lucas-C** [comment]
This seems to still be considered vulnerable by Snyk, as of today: https://snyk.io/vuln/npm:ng-dialog
I do not know how to report to them that it is fixed by now though

**Comment by tommarien** [comment]
I've just send a tweet to snyk asking to reeval this thing ;), sorry for the issue

**Comment by lirantal** [comment]
oh thanks for pinging us, we're on it!

**Comment by tommarien** [comment]
@lirantal Thanks, no longer considered vulnerable by Snyk
