### ISSUE TITLE
request: add onBeforeOpen function

### ISSUE THREAD

**Issue by mattiLeBlanc** [likeastore/ngDialog#509]
Hi,

Would you agree it would be nice to add an onBeforeOpen function to the dialog.open() function so that I can do some dom manipulation just after the the modal has been added to the DOM but not yet visible.
The only way now catching the event 'ngDialog.opened' on $rootScope. But I don't want to use any scope (angular 2 ready?).

**Comment by ashubham** [comment]
+1

@mattiLeBlanc Do you happen to have any fork where you tried implementing this. events and scope are ugly.

**Comment by mattiLeBlanc** [comment]
ouch, it has been a while so I have to remember where I needed this option. I might have found a way around this. Let me come back to you on this, kay?

**Comment by faceleg** [comment]
Moving conversation to the PR
