### ISSUE TITLE
get the data from ngDialog

### ISSUE THREAD

**Issue by WoShiSunWuKong** [likeastore/ngDialog#524]
**What version of ng-dialog are you using?**
　　　　 **"ng-dialog": "0.6.1"**
**What version of AngularJS are you using?**
　　　　**"angular": "1.5.8"**
　　
**Please describe the issue**
　　　　the dialog has a input element,I want get the value,this is the ngDialog Template
　　　　![ngDialog Template](https://cloud.githubusercontent.com/assets/16789187/20738559/0542f214-b6ef-11e6-9206-6ee169e3d974.png)
　　　　then ,open the dialog 
　　　　![image](https://cloud.githubusercontent.com/assets/16789187/20738621/755383ca-b6ef-11e6-9c56-6171b364b2d1.png)

　　　　when close the dialog ,i want get the data from NgDialog，how to do it？
![image](https://cloud.githubusercontent.com/assets/16789187/20741773/4c362b2e-b707-11e6-856f-71f905596798.png)

thank you

**Comment by faceleg** [comment]
This would be a great question for stackoverflow.com
