### ISSUE TITLE
Provided ngDialog Sections?

### ISSUE THREAD

**Issue by deadmann** [likeastore/ngDialog#527]
**What version of ng-dialog are you using?**
Last NPM Package

**What version of AngularJS are you using?**
1.5.8

**What browsers are affected?**
Chrome / FF

**Please provide either a JSFiddle, Plunkr example that replicates the issue**

 _ 

**Please describe the issue**
I want to know if the dialog provider provide any header/action/footer panel/container/class beside the content container? and the best way to categorize theme...
for example in old dialog we used something to specify if they are modal, then we used some background, then we specified the base of modal, and inside it we had 2/3 section header, content, and actions (footer)...

And please don't say you should use h3/h1... cause when i use it the title come below close button instead of beside it...

i want to do something like:

dialog-header/dialog-body/dialog-footer under ngdialog-content tag

**What did you expect to happen?**

 _ 
 
**What actually happened?**

 _

**Comment by faceleg** [comment]
ngDialog doesn't provide any structure to the inner container.

You may investigate the wrapping elements by inspecting an instantiated dialog in chrome dev tools
