### ISSUE TITLE
Please update alone with Angular 1.6.0

### ISSUE THREAD

**Issue by reevelau** [likeastore/ngDialog#528]
Angular 1.6.0 has been release on 8-Dec. So far no noticeable issue was found when using ngDialog. 
[Release Notes](https://github.com/angular/angular.js/blob/master/CHANGELOG.md) 

But just **bower install** reports conflict when executing.

**What version of ng-dialog are you using?**
0.6.4

**What version of AngularJS are you using?**
1.6.0

**What browsers are affected?**
no obvious issue

**Please provide either a JSFiddle, Plunkr example that replicates the issue**

**Please describe the issue**
bower install reports conflict

But I can workaround the prompt with this bower configuration
`
  "resolutions" :{
    "angular": "~1.6.0"
  }
`

**What did you expect to happen?**
no

**What actually happened?**

**Comment by faceleg** [comment]
Please submit a PR with this change, I'll merge it

**Comment by reevelau** [comment]
I can do that, but could you briefly tell me the dev environment requirements? like how to run the tests? how many tests? Thanks!!!

**Comment by faceleg** [comment]
Done
