### ISSUE TITLE
Is there a way to check if the current page have any ngDialog instance?

### ISSUE THREAD

**Issue by yaoyonstudio** [likeastore/ngDialog#538]
Is there a way to check if the current page have any ngDialog instance?

Here's the situation. Android have a physics return key, and H5 can't detect(listen) it.
So when a modal open, I press the physics return key, the whole page push out, but the modal still open, but the page already leave.

I want when the physics return key pressed, close the modal first. and press again, leave the page(state).

need help, thank you guys.

**Comment by faceleg** [comment]
You could try `ngDialog.closeAll()` https://github.com/likeastore/ngDialog#closeallvalue
