### ISSUE TITLE
Does ng-Dialog support drag & drop to add files ?

### ISSUE THREAD

**Issue by chetanbuddh** [likeastore/ngDialog#542]
**What version of ng-dialog are you using?**

**What version of AngularJS are you using?**

**What browsers are affected?**

**Please provide either a JSFiddle, Plunkr example that replicates the issue**

**Please describe the issue**

**What did you expect to happen?**

**What actually happened?**

**Comment by faceleg** [comment]
This module provides a dialog only and will never do anything more. 

The functionality you mention should be implemented in your application code.
