### ISSUE TITLE
Weird close button icon

### ISSUE THREAD

**Issue by flashjammin** [likeastore/ngDialog#549]
**What version of ng-dialog are you using?**
1.1.0

**What version of AngularJS are you using?**
1.5.8

**What browsers are affected?**
Chrome

**Please provide either a JSFiddle, Plunkr example that replicates the issue**
https://plnkr.co/edit/5PvGjetjBMnZwcMnnePx?p=preview

**Please describe the issue**
I'm getting a funny close button in the top left corner with the x content sitting outside of it.

**What did you expect to happen?**
Not have the grey x content outside of the button

Is this happening to other people?

![image](https://cloud.githubusercontent.com/assets/7479498/26140170/4aff5856-3b29-11e7-94cc-9d82a045d52d.png)

**Comment by jeremiebernard** [comment]
You should take a look at this commit : https://github.com/likeastore/ngDialog/commit/5213b3411ef2a1a76e43b4318aa3672734c667ed

Try applying those rules to your ngdialog-close class :
```
.ngdialog-close {
    -webkit-appearance: none;
    background: none;
    border: none;
}
```

**Comment by flashjammin** [comment]
Thats done the trick. Thanks
