### ISSUE TITLE
Scrollbars not clickable on overflow

### ISSUE THREAD

**Issue by unluckynelson** [likeastore/ngDialog#552]
When a dialogbox is bigger than the window there are scrollbars on the side to scroll up or down. But when you click the scrollbars the ngDialog dissappears. 
Is there any work around or solution for this?

The problem can be reproduced by going to: http://likeastore.github.io/ngDialog
and clicking the demo. Resize the window until the scrollbars appreas and try and click on them.

This is a problem for users that do not have a middle-mouse scroller button and need to click on the scroll bars to get further down on the dialog box

**Comment by dpicode** [comment]
I've fixed this problem.

Here is the solution.
https://github.com/likeastore/ngDialog/pull/553

**Comment by unluckynelson** [comment]
Thank you! solution works!

**Comment by dmitry-zaets** [comment]
Looks like this fix got lost somehow, can it be reapplied please?

**Comment by DmitriiGaidukov** [comment]
@dpicode,  I've run into the same problem, but I'm using bootstrap classes, such as "modal-dialog" "modal-content" etc. Please, tell me where I can find a good demo of applying bootstrap dialog classes inside ngDialog.

upd. for now fixed with this ad hoc solution:

 .ngdialog {
        overflow: visible !important;
    }
    .modal-body{
        max-height: calc(100vh - 200px);
        overflow-y: auto;
    }
