### ISSUE TITLE
The dialog closes when you click on the scrollbar of the browser 

### ISSUE THREAD

**Issue by HighnKein** [likeastore/ngDialog#578]
ngdialog : 1.4.0

Angular: 1.6.5

Browser affected : Chrome (didn't try others yet)

When the content of a dialog is too long to fit in the browser, the vertical scroll bar of chrome shows. When you try to use the scrollbar by clicking on it the dialog close. It closes the same way that if you clicked outside of the dialog. 
When you use the mousewheel there's no problem.

How can I fix that ? Thanks

**Comment by RokoArtemMironov** [comment]
I have the same issue

**Comment by zhang-yafei** [comment]
I have the same issue,scrollbar can't be selected.I can only use the mouse roller.

Hi,guys,@HighnKein @RokoArtemMironov  I found a solution.This [https://github.com/likeastore/ngDialog/issues/521](https://github.com/likeastore/ngDialog/issues/521)

```
.ngdialog-overlay {
	display: none;
}
.ngdialog {
	background: rgba(0, 0, 0, 0.4);
	animation: ngdialog-fadein 0.5s;
}
```

**Comment by HighnKein** [comment]
@zhang-yafei 
thanks for the tip ! But with your solution you can't click out the modal to autoclose. 
But it works :)
