### ISSUE TITLE
Scrollable on entire page

### ISSUE THREAD

**Issue by aschmi** [likeastore/ngDialog#63]
Hi there,

do you see a good way to allow for vertical scrolling outside of the dialog-content itself, i.e. on the overlay? 

My Problem is that I've got a dialog which needs to be scrolled and it is kind of confusing that this is only possible if the cursor is over the dialog. I tried to work around this problem by giving the content 100% width and making its background transparent. However, this has a negative effect on the `closeByDocument` behavior (as it doesn't really work any more :smirk:). I want both, full page scrolling and clicking outside the dialog to close.

Do you get the picture?

Thanks in advance

**Comment by sejoker** [comment]
@voronianski the issue with scrolling is reproduced in the latest 0.3.11 version, is it regression bug? I could make PR with similar fix that @bgse did.

**Comment by lagr** [comment]
@sejoker A non-intrusive fix that uses the mechanism of @bgse's solution would be to add ```ngdialog-overlay``` to the className option and disabling the overlay via option. I have not tested this in depth, but it works quite well for me.

```js
ngDialog.open({
          template: '...',
          className: 'your-custom-classes ngdialog-overlay',
          overlay: false,
          controller: [...]
        });
```

**Comment by sejoker** [comment]
@lagr thanks I also implemented similar aproach in my project. I was interested in adding the fix into the main branch.

**Comment by thbsolutions** [comment]
Please fix it, this bug is really annoying  :(

**Comment by zaidiqbalvf** [comment]
Bug is still open for iPhone Webkit. I am getting this issue on iOS Hybrid app
