### ISSUE TITLE
Background tabbing still works while dialog is up

### ISSUE THREAD

**Issue by yoaquim** [likeastore/ngDialog#70]
Maybe I'm missing something, but if I open a dialog, I can still tab around in the background and interact with other elements; it so happens I have a view where there are multiple items, and each one of them can summon a dialog.

The real issue comes along when I tab around in the background and open up other dialogs - they start stacking up and the screen dimmer obviously gets darker and darker. I can work around this, but it'd be ideal if we could disable tabbing once a dialog crops up, or takes priority, so as to stack dialogs on top of each other and still only be able to interact with the topmost. 

Any ideas?

**Comment by mc-suchecki** [comment]
@voronianski - are you planning to add an option to block background tabbing?

**Comment by voronianski** [comment]
@mc-suchecki not now.. please make pull-requests for features/bugs.
