### ISSUE TITLE
closeByEscape closes dialogs it shouldn't

### ISSUE THREAD

**Issue by joelstein** [likeastore/ngDialog#86]
I think I found a bug. If I open a dialog with `closeByEscape: false`, and then open a second dialog without this option (thus defaulting to true), typing the "escape" key will close both modals. The expected behavior is that the first modal wouldn't be closeable via the escape key.

See it in action here:
http://jsfiddle.net/joelstein/rsdeufgz/

**Comment by tgelu** [comment]
+1

**Comment by saadlu** [comment]
+1

>  I think my expected behavior is that typing the "escape" key would only close the top dialogs, but it closes all of them.

Exactly my expectation and that's why I am here.

**Comment by bchelli** [comment]
:100: 
This is good news this is bugging me in my app
Thanks @jemise111
