### ISSUE TITLE
Two way binding not working when updating from ngDialog

### ISSUE THREAD

**Issue by nimmyks87** [likeastore/ngDialog#93]
Here is the code for opening Dialog.
$scope.orders =[];
$scope.open = function () {
		ngDialog.open({ template: 'openOrderDialog', controller: 'OrderController',scope: $scope});
	};
There is a create order button in my Dialog, on click of that I need to update the $scope.orders with response.

	$scope.OnCreateOrder = function(){
		//Create Order
		$http({method: 'post',
		url: '/orders',
		headers: {'Content-Type': 'application/json'},
		data:{quantity: 25,user='Bob'}
	})
		.success(function(response){
			$scope.orders.push(JSON.parse(response));
			ngDialog.close();
		});
    };

$scope.order is updating but the two way binding is not happening($scope.order I'm binding to a table) I'm doing something wrong? Any clues?

**Comment by egor-smirnov** [comment]
@devinmcinnis solution seems good for me. Feel free to open a new issue in case of questions like this as this issue is quite old.
